govuk-one-login/di-account-management-backend

lambda/.gitignore
lambda/write-user-services/index.ts
lambda/write-user-services/jest.config.ts
lambda/write-user-services/package-lock.json
lambda/write-user-services/package.json
lambda/write-user-services/tests/index.test.ts
lambda/write-user-services/tsconfig.json

This lambda doesn't do anything useful at the moment (it just logs the contents of the event body), but it *should* be deployable and this PR sets up the file structure and a simple unit test which we can build on.
I mostly followed the [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/typescript-handler.html) and the [Jest getting started guide](https://jestjs.io/docs/getting-started) to get this working, plus I stole a bit of config from [TxMA's event processing lambda](https://github.com/alphagov/di-txma-audit/tree/main/event-processing/lambda). Each commit has more details on what's going on.
I hope all we need to do for the other lambdas we write is copy the config files over to folders, install the same dev dependencies and get coding 🤞🏻 
I went back and forth on the name for …

GUA 426: Set up the 'write user services' lambda

---

lambda/write-user-services/tsconfig.json

VSCode couldn't find the Jest types, so was giving us errors in all the test files.
This commit adds Jest to the `tsconfig.json` and removes the test files from the exclude. This solves the IDE problems but means we're including the test files in the complied Javascript.
That's not ideal either, but we're a way off deploying these to production so we'll fix it later.
https://stackoverflow.com/questions/54139158/cannot-find-name-describe-do-you-need-to-install-type-definitions-for-a-test

BAU: Fix Jest errors in IDE

---

lambda/write-user-services/index.ts
lambda/write-user-services/models.ts
lambda/write-user-services/package-lock.json
lambda/write-user-services/package.json
lambda/write-user-services/tests/index.test.ts

This PR sets up the 'happy path' for the lambda function to write events to DynamoDB. There's a function and test to do data structure validation, but it always returns `true` at the moment. I'll tackle that, error handling and logging in my next PRs.  
I've used the interfaces Huw wrote for the data structures. They're good, but I'm not completely sure about the file structure I've gone with here. I'm also pretty confident that this will work when deployed thanks to the type system, but there might need to be some tweaks when we get to that step, since I can't test deploying it at the moment.

GUA-426: Set up 'happy path' for writing to DynamoDB

---

lambda/write-user-services/.eslintrc.json
lambda/write-user-services/models.ts
lambda/write-user-services/package-lock.json
lambda/write-user-services/package.json
lambda/write-user-services/tests/write-user-services.test.ts
lambda/write-user-services/write-user-services.ts

This PR sets up linting for the `write-user-services` lambda function using ESLint and following the Airbnb style guide. 
You can now run the linter with `npm run lint`. IDEs with ESLint and Prettier plugins should also pick up the config file and display errors along with the code.
This isn't used for CI at the moment, but it sets us up to be able to enforce the style guide on PRs in the future.
---
I was hoping to be able to put the `.eslintrc.json` file further up in the file structure, but unfortunately ESLint wasn't happy with that. I think it was looking for a `node_modules/` folder in the same place as the config file which we don't have, and I didn't want to add another place to keep dependencies up to date.
Instead we'll have to copy the config file across to each lambda and …

BAU: Set up linting following the Airbnb style guide

---

infrastructure/template.yaml
lambda/write-user-services/package-lock.json
lambda/write-user-services/package.json
lambda/write-user-services/tests/write-user-services.test.ts
lambda/write-user-services/write-user-services.ts

Update the Cloudformation to pass the SQS queue URLs through as environment variables, not ARNs, since the SQS SDK needs the URL. 
Then add logic to the handler which puts any event which caused an error onto the dead letter queue without modifying or trying to parse it.

GUA-426: Send events that cause an error to the DLQ

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/lint-cloudformation.yaml

These will run when a pull request is opened and run linting and the unit tests for each lambda, plus lint the Cloudformation template.
To add the other lambdas we'll just need to copy the whole job and change the `working_directory` value for each.
It's possible that the lambda action ends up taking a long time to run, particularly if we end up with a lot of lambdas in this repo, or if some of those lambdas have a lot of dependencies.
If that happens we can look at splitting this action up or caching dependencies [1], but I don't think we need to do that right away.
[1]:https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

GUA-436: Set up CI for Cloudformation and `write-user-services` lambda

---

.github/workflows/lint-cloudformation.yaml
.github/workflows/skip-lint-cloudformation.yaml

Use the `paths` filter [[1]] to skip the Cloudformation lint check if no files have changed in the `infrastructure/` folder.
In order to have this check as a 'required check' before a PR can be merged, we also need to add a second action, with a job of the same name that *only* runs when no files have changed in the `infrastructure/`folder [[2]].
There are still two passing checks on this PR, but the logs for Cloudformation linter one show that it's run the new action and not any checks (as expected, since this PR doesn't change any infrastructure code).
[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
[2]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-reposito …

GUA-436: Skip infra tests when unchanged

---

lambda/format-user-services/package-lock.json
lambda/format-user-services/package.json

This was the case in format-user-services lambda, somehow it had made it into both and that fact was causing `sam build` to fail

BAU: Move @aws-sdk/client-sqs out of devDependencies

---

infrastructure/template.yaml
lambda/format-user-services/format-user-services.ts
lambda/format-user-services/models.ts
lambda/format-user-services/tests/format-user-record.test.ts
lambda/format-user-services/tests/testHelpers.ts
lambda/query-user-services/query-user-services.ts
lambda/query-user-services/tests/query-user-services.test.ts

This PR fixes several small bugs to get the lambda functions all working together. We can now put an event on the input queue, see it processed by each lambda and end up in DynamoDB. 
The largest bug was that we weren't resolving the `Promise`s in the handler function for the first two lambdas, which meant the lambda stopped running before the messages got put on the queue to the next lambda. We were iterating over each record using `.forEach`, but that doesn't collect the returned objects and so discards the `Promise`s. We've now switched to `Records.map` which returns an array of `Promise`s, which we then wait to resolve using `await Promise.all( ... )`. 
We may want to tweak this behaviour in the future (perhaps with [`Promise.allSettled()`](https://developer.mozilla.org/en-US/docs/Web/ …

GUA-448: Get the happy path working for lambda functions

---

LICENCE
README.md

We can add to the README as we work more things out - for example end-to-end tests or running a Lambda locally.

BAU: Add initial README and licence

---

lambda/format-user-services/tsconfig.json
lambda/query-user-services/tsconfig.json
lambda/write-user-services/tsconfig.json

We removed the `exclude` directive for the test files in #2 to get VSCode to recognise that tests were run with Jest and not show errors for unknown functions.
Further testing has shown we only need the extra `types` entry added there, and VSCode is happy when the test files are added back to the exclusion list.
This change doesn't seem to have reduced the size of the deployed Lambdas like I was expecting. `sam build` uses ESBuild under the hood to transpile Typescript into Javascript and it's possible that was already ignoring the test files. In either case this change does make our config more similar to other teams on the programme.
---
To review, checkout this branch, open a test file in VSCode and check that it's not full of error messages when we use `describe()` or `test()`.

GUA-438: Exclude test files from deployed Lambdas

---

lambda/format-user-services/format-user-services.ts
lambda/format-user-services/tests/format-user-services.test.ts
lambda/query-user-services/query-user-services.ts
lambda/query-user-services/tests/query-user-services.test.ts

This PR adds the Dead Letter queue configuration to the format user service and query user service lambda. 
- If an error of any kind occurs during the process the record is sent to the Dead Letter Queue.
- I have also included some fix for linting errors in `format-user-services.test.ts` regarding an unused var.
- Also renamed format-user-record.test to format-user-service to match the handler ts.

GUA - 431 dead letter queues

---

infrastructure/template.yaml

Set up a Cloudwatch alarm for each of the dead letter queues that's triggered when there's at least one message unprocessed in the queue.
The `ApproximateNumberOfMessagesVisible` metric seemed the most appropriate of those available [[1]. It's an approximation, but it'll always be greater than 0 if there's at least one message which is fine for this use case where we don't care how many messages there are.
There was also `NumberOfMessagesSent` which is "The number of messages added to a queue" but I wasn't sure if that would also be triggered if the whole Lambda failed to run and AWS put the message onto the DLQ, rather than us calling `sendMessage` from inside the lambdas.
For now these alarms don't do anything - we'll tackle sending notifications to Slack in future PRs.
---
I've …

GUA-432: Trigger alarms when the DLQs receive a message

---

infrastructure/samconfig.toml
infrastructure/template.yaml

Set up AWS Chatbot to send messages to our Slack channel, mostly following what the dev platform pipeline [[1]] already does. Then add actions to each of the alarms to send a message to the new SNS topic when they're triggered.
This puts a message in Slack when an alarm goes off - see an example [here](https://gds.slack.com/archives/C011Y5SAY3U/p1666615861541789). Since that test message we've added the environment name to the alarm name so it's obvious which environment the alarm is for.
This Slack message topic and Chatbot config are prime candidates for moving to the central infrastructure stacks the Bravo team are writing. We may even not need the Chatbot config as one also gets created for the pipeline. We can consider that refactor when the central templates are ready.
[1]: …

GUA-432: Send a message to Slack when an alarm is triggered 

---

infrastructure/template.yaml

If a Log Group is not declared within CloudFormation, then this Log Group will be automatically created at run time and it won’t be managed by CloudFormation. The consequences are that the:
- Log Group will not be removed when the Stack is removed.
- Log Group attributes (such as retention) won’t be managed "as code" within CloudFormation.
These automatically created Log Groups will remain forever which can have huge impact on costs and security (the data stay forever while this is unexpected from company or regulatory rules).
A good practice is to declare the target Log Group with CloudFormation, matching the name that the AWS will use so that the Log Group resource is managed as code.

Add Log Group for Aws Serverless Functions

---

.github/workflows/sam-app-post-merge-actions.yaml

We removed this restriction while we were setting up the deploy action and missed adding it back before we merged.
Add it back so this action only runs when a pull request is merged to `main`.

GUA-435: Restrict deploy action to `main`

---

README.md

Adds `esbuild` as a dependency since this is required for `sam build`.
Also add instructions to send a test event to the application's input queue.

BAU: Update prerequisites and testing instructions

---

infrastructure/template.yaml

Custom log group names are not allowed in AWS and they follow the pattern of /aws/lambda/{functionName} . Add function name to the lambdas to create the correct Log Group Name. 
Thanks to @alex9smith

Add function name to Lambda to create a log group 

---

infrastructure/template.yaml

- Only allow lambda to perform creation actions when encrypting and decrypting. 
- Remove other policies that are not needed .

GUA 499 : Update the permission of key on Lambda Policy

---

infrastructure/template.yaml

Sets up log subscription filters that send application logs from the lambdas to Splunk.
These aren't created in the `dev` AWS account. We don't have a CSLS config for `dev` and it doesn't make sense to create one since we share the non-production index with all environments and teams on DI. We don't want to accidentally fill that index with logs from our development environment while we're testing things out.
Because of that we'll have to test in `build` after merging this PR. That should be ok though, I'm pretty confident in these changes.

GUA-512: Send lambda logs to Splunk

---

lambda/delete-user-services/delete-user-services.ts
lambda/delete-user-services/tests/delete-user-services.test.ts
lambda/delete-user-services/tests/testHelpers.ts

1. Pre-populate a dynamoDB record with our target user_id
```bash
gds aws di-account-dev -- aws dynamodb put-item \
--table-name user_services \
--item '{ "user_id": { "S": "test-to-delete"}}'
```
Or, [create an item in the AWS console](https://eu-west-2.console.aws.amazon.com/dynamodbv2/home?region=eu-west-2#edit-item?table=user_services&route=ROUTE_ITEM_EXPLORER&itemMode=1) with `user_id` = "test-to-delete"
2. Query to check that your new record is there:
```bash
gds aws di-account-dev -- aws dynamodb get-item \
--table-name user_services \
--key '{"user_id": {"S": "test-to-delete"}}'
```
or to see all entries:
```bash
gds aws di-account-dev -- aws dynamodb scan --table-name user_services
```
You can also explore the [AWS console …

GUA-469 delete lambda

---

lambda/format-user-services/format-user-services.ts
lambda/query-user-services/query-user-services.ts
lambda/write-user-services/write-user-services.ts

Really Oddly we're seeing some test flake on CI:
- [Job  before](https://github.com/alphagov/di-account-management-backend/actions/runs/3445066252/jobs/5748350316)
- zero code change, [after re-running](https://github.com/alphagov/di-account-management-backend/actions/runs/3445066252/jobs/5748468073)
What on earth? How is there any state here to flake over?
My best bet is that the test order is somehow throwing things out, and
that the environment variable is the core bit that can vary here?
So let's amend this function to be in line with: https://github.com/alphagov/di-account-management-backend/commit/24bd4947089d12ba04b9c3e2e99f662236e3f3ea

Bau attempt to fix test flake

---

infrastructure/template.yaml

This table has streams [[1]] enabled, which will become the input trigger for the `query-user-services` lambda. Items in this table will be written once and not updated, so I've used the `NEW_IMAGE` stream setting which will only include the newly written data in the stream event.
The table also has two keys - `id` and `timestamp`. DynamoDB requires a hash key that's used for the primary index. We don't want the lambda that writes these items to parse the TxMA event because that might fail, so we'll need to generate this ID in the lambda.
We're also using `timestamp` as a RANGE key. If we do ever need to use this table to replay events, it'll probably be over a time range. Using the timestamp as a key gives us a secondary index that'll speed up time-based queries.
We want to use Dynamo's …

GUA-487: Create DynamoDB table for raw events

---

infrastructure/template.yaml

WIP whilst I test
Check the topic SQS DLQ exists:
https://eu-west-2.console.aws.amazon.com/sqs/v2/home?region=eu-west-2#/queues/https%3A%2F%2Fsqs.eu-west-2.amazonaws.com%2F985326104449%2Faccount-mgmt-backend-UserAccountDeletionTopicDeadLetterQueue-gZpDthtNx75m
Check an Alarm is present for the DLQ:
https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#alarmsV2:alarm/account-mgmt-backend-dev-UserAccountDeletionTopicDeadLetterQueueAlarm?
Check that the it is not in the alarm state.
```
gds aws di-account-dev -- aws sqs send-message --queue-url https://sqs.eu-west-2.amazonaws.com/985326104449/account-mgmt-backend-UserAccountDeletionTopicDeadLetterQueue-gZpDthtNx75m --message-body "Test the alarm system"
```
Check that there is [1 message on the …

GUA-468 delete stack alerting

---

infrastructure/template.yaml
lambda/query-user-services/query-user-services.ts
lambda/query-user-services/tests/query-user-services.test.ts

Switches the first lambda in the user services pipeline to use the DynamoDB table stream added in #44. This is part of the work to update the system architecture to reflect [ADR 0004](https://github.com/alphagov/di-account-management-backend/blob/main/docs/adr/0004-store-all-event-data.md).
This lambda is only subscribed to events when new items are written to the table. We're also enabling DynamoDB's TTL feature on this table, and we don't want the delete events from that to cause errors or (worse) be treated as new events.

GUA-487: Switch user services pipeline to Dynamo stream

---

infrastructure/template.yaml

These need to be in place because CloudFormation evaluates both sides of the if statement for the queue ARN on line 190 before filling in the correct value.
If there's not a value in the mapping for each environment the template fails to deploy with an error like
```
Status: FAILED. Reason: Template error: Unable to get mapping for InputQueue::build::QueueArn
```
Also change the condition so that it's only true for staging at the moment. This hasn't caused any errors yet, but it would have done if the template had got as far as integration.

GUA-514: Set values for `QueueArn` in all environments

---

infrastructure/template.yaml

We'll need to be able to get this ARN into our frontend stack, but as the cloudformation lives in separate template files, the way we're going to exchange it is to have this deploy write the ARN to an SSM parameter, which we can then call out of the frontend stack.

GUA-470: Add the SNS topic ARN as a SSM parameter

---

infrastructure/template.yaml

We'll need to pick up on this in the frontend application

GUA-470: Ship the SNS KMS Key ID as an SSM parameter

---

README.md
docs/adr/0003-recording-service-usage-in-account.md
lambda/format-user-services/format-user-services.ts
lambda/format-user-services/models.ts
lambda/format-user-services/tests/format-user-services.test.ts
lambda/format-user-services/tests/testHelpers.ts
lambda/query-user-services/models.ts
lambda/query-user-services/query-user-services.ts
lambda/query-user-services/tests/query-user-services.test.ts
lambda/save-raw-events/models.ts
lambda/save-raw-events/save-raw-events.ts
lambda/save-raw-events/tests/save-raw-events.test.ts
lambda/write-user-services/models.ts
lambda/write-user-services/tests/write-user-services.test.ts

Update TxMA event payload expectations, broadly:
- remove component_id, that's no longer coming through
- update TxMA payloads to reflect data we know we're getting
- keep validation to only things we know we want to use
- Cascade dates through the system as Epoch numbers, as I'm suspicious about `Date` class instances making it back when we're coming in and out of Dynamo and JSON parsing. Let's expect numbers, parse them as epochs where we need them

GUA-514 changes to txma data model

---

lambda/format-user-services/format-user-services.ts
lambda/format-user-services/models.ts
lambda/format-user-services/tests/format-user-services.test.ts
lambda/format-user-services/tests/testHelpers.ts
lambda/query-user-services/models.ts
lambda/query-user-services/tests/query-user-services.test.ts
lambda/write-user-services/models.ts
lambda/write-user-services/tests/write-user-services.test.ts
lambda/write-user-services/write-user-services.ts

The frontend is fairly naively consuming payloads out of dynamo.
To prevent complicating the controller / view, let's just add another field of formatted data.
Called it pretty becuase TxMA already has a ISO string with suffix `_formatted`, `_pretty` is intended to distinguish.

GUA-462 Prettify dates

---

infrastructure/template.yaml

- Add ReservedConcurrentExecutions to the lambda functions to avoid checkov  error on build . 
We can see that in there are 4 events published per sec and by keeping the value of the ConcurrentExecutions at 10 we allow room for 20 events/sec. which is way above what we are seeing.

Fix checkov error on build pipeline add ReservedConcurrentExecutions to lambda function 

---

.github/workflows/lint-cloudformation.yaml
.github/workflows/sam-app-post-merge-actions.yaml

Proposed changes
Updating github workflow actions to versions written in Node 16.
Why did it change
Github is deprecating Node12 and for security deprecating the set-output function.
Checklists
Checked workflows that are triggered when branch is pushed, when deploying to dev, and when raising PR.
Workflows triggered on merge to main can only be confirmed when this PR is merged.

GUA-524 updating github workflow actions to node16 versions

---

.github/workflows/sam-app-post-merge-actions.yaml

Proposed changes
GUA-524 updating git workflow 'checkout' action to node16 version
Why did it change
Github is deprecating Node12 and for security deprecating the set-output function.
Missed this one in previous PR because this workflow is not called till after merge to main. 
Checklists
Checked workflows that are triggered when branch is pushed, when deploying to dev, and when raising PR.
Workflows triggered on merge to main can only be confirmed when this PR is merged.

GUA-524 updating git workflow 'checkout' action to node16 version

---

.gitignore
infrastructure/samconfig.toml
infrastructure/template.yaml
lambda/.gitignore

Give `SNS` permission to access the `QueueKmsKey` so that it can send undeliverable messages to the `UserAccountDeletionTopicDeadLetterQueue`. Also adding `.idea` folder to `.gitignore`. 
Permission was added to the `QueueKmsKey` resource to allow `SNS` to access this key.
The `UserAccountDeletionTopic` is not sending to the `UserAccountDeletionTopicDeadLetterQueue` messages which it cannot deliver to the `DeleteUserServicesFunction` because it does not have permission to access the `QueueKmsKey`. 
- [ATB-233](https://govukverify.atlassian.net/browse/ATB-233)
https://user-images.githubusercontent.com/110468919/216605712-2d9fe9c5-7573-4916-90dc-d7771b9d11e1.mp4
[ATB-233]: https://govukverify.atlassian.net/browse/ATB-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …

ATB-233: Added permission to QueueKmsKey resource so that SNS can access key and send undeliverable messages to the DLQ

---

infrastructure/template.yaml

- Update the processor Architecture to `arm64` .
- Link to [ADR](https://github.com/alphagov/digital-identity-architecture/pull/365/files) 
- Tested this on dev .
- Check weather the Cloud Formation [template](https://eu-west-2.console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stacks/template?filteringText=backend&filteringStatus=active&viewNested=true&stackId=arn%3Aaws%3Acloudformation%3Aeu-west-2%3A985326104449%3Astack%2Faccount-mgmt-backend%2F69df82c0-b1eb-11ed-8e82-0233824c9288) is updated with the relevant changes.
**Steps to Test** 
**Step 1** : Make sure this branch is deployed on dev . Since dev is on control tower follow [steps](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3364586065/SSO+with+IAM+Identity+Centre+and+Control+Tower#3.-SSO-Access-to-a-Control-T …

GUA-697 Update processor Architecture to arm64

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/lint-cloudformation.yaml
.github/workflows/publish-to-dev.yaml

- Fix errors in the worfkflow 
- Other workflows included to run on dev should also include the trigger .
- Updating the Github Action Role Arn to point to Dev 
- Update the working directory for sam build, validate and deploy.
- Create a AWS-Signer (https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3377004573/AWS+Signer) 
- Update the Signer Profile and Signer Version Arn on the backend Pipeline stack to pick up the Github Role Policies.
See successful run - https://github.com/alphagov/di-account-management-backend/actions/runs/4415426803/jobs/7739187222
Code Pipeline Run - https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/985326104449/projects/Deploy-account-mgmt-backend-pipeline/build/Deploy-account-mgmt-backend-pipeline%3A243a4e9b-fe84-41dc-bbbe-c5a707e4e7d8/?region=e …

GUA- 711 : fix workflow

---

infrastructure/template.yaml

- Rename the LogGroup Name to be consistent with the other lambas. 
Note: I had to delete the old Log group otherwise the deploy fails with error 
```
Resource handler
DeleteUserServicesFunctionLogGroup   
returned message:
"Resource of type 'AWS::Logs::LogGroup'
with identifier '{"/properties/LogGroupName" :"/aws/lambda/dev-account-mgmt-backend-delete-user-services"}' already exists."(RequestToken: aa8edfeb-ad5d-27f1-54bf-93f839c6450c, HandlerErrorCode: AlreadyExists)
```
https://stackoverflow.com/questions/56137460/an-error-occurred-loggroup-resource-name-already-exists-while-trying-to-d

GUA-705 Update Log Group Name for Delete User Services

---

lambda/save-raw-events/tests/save-raw-events.test.ts

Tidies up the Validator tests for the Raw Events store lambda.
We'll likely need to look at similar improvements to the other lambdas.
In this case tests were passing because the user validator check was throwing, when we'd hoped it was the txma body check.

BAU: Fix validator tests

---

lambda/query-user-services/query-user-services.ts
lambda/query-user-services/tests/query-user-services.test.ts
lambda/query-user-services/tests/test-helpers.ts

Block off the query pipeline to any event other than AUTH_AUTH_CODE_ISSUED at a time where we're expanding the raw event store.

GUA: 746: Ensure only auth auth code for service cards

---

lambda/shared-models.ts

[https://govukverify.atlassian.net/browse/GUA-748]
Add a shared models file for multiple lambdas to use. staring with the activity log lambdas.
File comtains models for TXMA events and for the activity log store.

add shared models file for activity log lambdas

---

lambda/save-raw-events/models.ts
lambda/save-raw-events/save-raw-events.ts
lambda/save-raw-events/tests/save-raw-events.test.ts
lambda/save-raw-events/tests/test-helpers.ts

This is part of extending the raw events store to handle events we will need to render the activity log. We'll want to use the AUTH_AUTH_CODE_ISSUED event, but be able to aggregate them by the earliest event grouped by a session_id.

GUA-746: Add Session ID to raw event store

---

infrastructure/template.yaml

Reverts alphagov/di-account-management-backend#97
We're having issues with the VPC and deploys, reverting this until we've got the base stack updated.

Revert "BAU: Add third subnet"

---

infrastructure/template.yaml

When deployed we were getting an error : https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/301577035144/projects/Deploy-account-mgmt-backend-pipeline/build/Deploy-account-mgmt-backend-pipeline%3A5d68cd1d-f816-4298-8f21-0fd6158bdb7e/?region=eu-west-2
`CloudFormation cannot update a stack when a custom-named resource requires replacing.Rename activity_log and update the stack again.`
Renaming the table name as per : https://repost.aws/knowledge-center/cloudformation-custom-name

GUA-748 : Update table name after change of sort key type

---

lambda/format-user-services/models.ts
lambda/format-user-services/tests/test-helpers.ts
lambda/query-user-services/models.ts
lambda/query-user-services/tests/test-helpers.ts
lambda/save-raw-events/models.ts
lambda/save-raw-events/tests/test-helpers.ts

Dependent on: https://github.com/alphagov/di-account-management-backend/pull/90
Removing this for two major reasons.
1. We're not really using it, and the principle of data minimisation is
a good one. I'd rather not be storing things unless I have a good use
or reasonable propect that we'll need it in future.
2. We currently support AUTH_AUTH_CODE_ISSUED, and are looking to add a
second event shortly in AUTH_IPV_AUTHORISATION_REQUESTED event.
According to the TxMA event spreadsheet
AUTH_IPV_AUTHORISATION_REQUESTED does not currently support
govuk_journy_id.
We want to try and keep these consistent so that we can validate for a
single TxMA Event shaped input, so I'll be changing these up in self
service to make them consistent.

GUA-746 - Remove govuk journey

---

docs/stubs/account-management-api/openapi.yaml

This OpenAPI specification defines the routes, requests and responses the stub will need to support.
It's a very simple stub with only 5 routes and it always returns an empty response with status 204, but it's worth documenting properly in case we need to make changes in the future. The schemas in particular are overkill since we don't really care about the request but it might save us some digging around later on. 
I've chosen to put this in the backend repo because the stub will effectively be a backend service and that's where I'm expecting us to put the code / Cloudformation for it as well. If we end up putting the stub code in the frontend repo then we should move this documentation there as well.

GUA-872: Add spec for Account Management API Stub

---

docs/stubs/oidc/openapi.yaml

Add specification for the OIDC server stub. This is mostly pulled from our public documentation on how to [understand the OIDC flow](https://docs.sign-in.service.gov.uk/how-gov-uk-one-login-works/#understand-the-technical-flow-gov-uk-one-login-uses) and how to [integrate with GOV.UK One Login](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/integrate-with-code-flow). OIDC is a pretty simple flow when we don't care about actually authenticating someone, so hopefully it's easy to follow.
This stub will be more complicated than the account management one. I think the trickiest bit will be the key management since it'll need to sign the JWT returned to the RP. Implementation details are out of scope for this PR however.
When writing this I realised the OpenAPI …

GUA-872: add OIDC stub spec

---

docs/adr/0007-architecture-for-stubs.md

We will be running performance (load) testing to see how our service scales. As part of this, we need to replace external dependencies with stubs. These stubs will be simple interfaces to replace eg. the Account Management API.
This ADR sets out options for the hosting and architecture of the stubs.
[Link to rendered Markdown](https://github.com/alphagov/di-account-management-backend/blob/GUA-873-adr-for-stubs/docs/adr/0007-architecture-for-stubs.md)

GUA-873: Add ADR for stub architecture

---

lambda/save-raw-events/save-raw-events.ts
lambda/save-raw-events/tests/save-raw-events.test.ts

This is one of the mitigations from our threat modelling session to reduce risk of data exposure in the raw event store. The system has been happily running for several months now and we're not going to need 90 days data to back fill anything.
14 days is still enough time for us to do any event replays if we have an outage over a period like Christmas where we may have several team members on leave.

BAU: Reduce raw events TTL to 14 days

---

infrastructure/template.yaml

This adds a new condition to use stubbed services in case we want to use them in dev in the future too.
This setup is broadly the same as the example stack I attached to PR #118 where I added the lambda. The only differences are the logging and other production-ready stuff like the permissions boundary and the VPCs.
I've intentionally not put a dead letter queue on this lambda because it's a standalone thing returning a static payload. We'll have enough info in the logs to debug any problems and it doesn't matter if we 'lose' the event data that triggered an error.
The API endpoint is saved to a parameter store value. I'll reference this in the frontend stack template to set the `AM_API_BASE_URL` environment variable
This change is deployed to dev at the moment. You can test the API with …

GUA-874: Deploy Account Management stub API to build

---

lambda/format-activity-log/format-activity-log.ts
lambda/format-activity-log/models.ts
lambda/format-activity-log/tests/test-helper.ts
lambda/query-activity-log/models.ts
lambda/query-activity-log/query-activity-log.ts
lambda/query-activity-log/tests/query-activity-log.test.ts
lambda/query-activity-log/tests/test-helpers.ts
lambda/write-activity-log/models.ts
lambda/write-activity-log/tests/test-helpers.ts
lambda/write-activity-log/write-activity-log.ts

I was checking that this was possible and I thought the easiest way to make sure was to do the work.
There's three commits here, changing the query, format and write lambdas in turn. It ended up being a fairly simple change but see the commit messages for more information.

OLH-1006: Save the event ID in the activity log

---

.github/workflows/sonarcloud.yaml

This commit SHA is v2.0.0 of the action - see https://github.com/SonarSource/sonarcloud-github-action/releases/tag/v2.0.0 We've been getting warnings that the version we were on before was using Java 11 which is very out of date (Java 17 is the current release).
Updating should get us a much newer version

BAU: Update Sonar to the latest action version

---

lambda/query-activity-log/models.ts

We're now receiving this event from TxMA which is triggered once a user successfully completes the ID proving journey and is passed back to Auth.
We'll want to show information to users about when they proved their ID in the activity log, so add it to the list of allowed event names.
See https://github.com/alphagov/di-txma-event-self-serve/pull/231

BAU: Save successful ID check event

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/lint-cloudformation.yaml
.github/workflows/require-pinned-github-actions.yml
.github/workflows/sonarcloud.yaml

Set a 15 minute timeout limit for all Github actions which don't just call other workflows or already have a different limit set.
See [the action docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) for more details.
We have a shared actions runtime quota across the whole Github organisation and if we hit the quota then actions will stop running completely. This would be a very bad time, so set sensible limits so we don't get a runaway action that runs for ages.
See also https://github.com/alphagov/di-account-management-frontend/pull/993

BAU: Set timeout for Github actions

---

lambda/delete-email-subscriptions/delete-email-subscriptions.ts
lambda/delete-email-subscriptions/tests/delete-email-subscriptions.test.ts

Remove user_id logging on Validation Failure 
Remove user_id logging on Validation Failure 
Cannot log PII data .

Remove logging userData on Validation failure

---

lambda/delete-email-subscriptions/delete-email-subscriptions.ts

Remove Logging that is not necessary. 
By logging the URL and Config the token and user data is being logged which is against PII data logging .

Remove logging that is not necessary

---

lambda/delete-email-subscriptions/delete-email-subscriptions.ts

Existing functionality treats anything other than a 2XX as an error . Any error message is sent to the DLQ
The change is to not allow a 404 request from the publishing API to be sent to the DLQ as this use case is common for users that have a service card that needs to be deleted and it is not a email subscriptions. Both the delete lambda and delete email subscriptions lambda consume from the same SNS topic.
The change was needed to allow the service to log the 404 and not send it to the DLQ.

OLH-1091: Add a filter for 404 status code to not be allowed in the DLQ

---

infrastructure/template.yaml
lambda/query-activity-log/decrypt-data.ts
lambda/query-activity-log/kms-keyring-builder.ts
lambda/query-activity-log/models.ts
lambda/query-activity-log/package-lock.json
lambda/query-activity-log/package.json
lambda/query-activity-log/query-activity-log.ts
lambda/query-activity-log/tests/decrypt-data.test.ts
lambda/query-activity-log/tests/kms-keyring-builder.test.ts
lambda/query-activity-log/tests/query-activity-log.test.ts
lambda/query-activity-log/tests/test-helpers.ts

Update the `query-activity-log` lambda to decrypt the user's activity history in the query result from DynamoDB. 
This closely follows the implementation of the encryption added in #142 with a few simplifications:
1. We don't need the backup key to decrypt. This meant I could simplify the keyring builder
2. This doesn't use the check value as part of the encryption context validation. I will add this later
We need to decrypt the user's history before we try to insert the new event. It made sense to do it in this Lambda since it's already making the query to DynamoDB - this lets us keep the format Lambda 'permissionless'. 
#142 
I am working on a test checklist to verify this in dev

OLH-904: Decrypt user activities before formatting

---

docs/manual-testing/manual-testing.md
infrastructure/template.yaml
lambda/query-activity-log/decrypt-data.ts
lambda/query-activity-log/tests/decrypt-data.test.ts

Add KMS permissions, the key ARN environment variables and decode the base64 string back into bytes.
This fixes the `query-activity-log` lambda for users who already have stored data.
#143 
I've deployed this branch to dev and sent some events to the dummy event store. You can see the successful invocations in [Cloudwatch](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdev-account-mgmt-backend-query-activity-log/log-events/2023$252F09$252F27$252F$255B$2524LATEST$255D60dae1a6bd4f4ef6885f6ad8f43d7fa5)

OLH-904: Fix decrypt lambda

---

docs/manual-testing/manual-testing.md
infrastructure/template.yaml

[OLH-1014] - decrypt activity log in front end 
separate commits:
- Add generator key and wrapper key IDs to SSM
- Correct manual testing file path
- Add key arns as environment variables on query-activity-log lambda 
Add key arns as environment variables to enable decryption. 
Add generator key and wrapper key IDs to SSM in order to make the 
[OLH-1014]: https://govukverify.atlassian.net/browse/OLH-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add generator key and wrapper key IDs to SSM

---

infrastructure/template.yaml

Following the guidance from TxMA[^1], this sets up an SQS queue that we'll send audit events to, a KMS key to encrypt the events at rest and a dead letter queue.
This uses the 14 day message retention policy recommended by TxMA.
The permissions here allow any resource from TxMA's accounts to consume messages from the queue and decrypt them with the KMS key. The account IDs come from TxMA's documentation[^2].
Right now nothing in our account has permission to write to the queue - we'll add these once we start working on producing events.
We're setting up as a new audit event producer since we need to generate events when a user takes action on the triage page. The first step in this process is to create these new resource, add them to the list of producers on Confluence and let TxMA know …

OLH-1118: Set up queues and key for audit events

---

infrastructure/template.yaml

Export the audit queue URL, ARN and key ARN as parameters to SSM.
We need to reference these from the frontend stack in order to pass the queue URL as an environment variable and give the ECS role permissions to write to the queue.
Export them as SSM parameters so we can import them into the other stack
I've [deployed to dev](https://eu-west-2.console.aws.amazon.com/systems-manager/parameters/account-mgmt-backend/SQS/AuditQueue/URL/description?region=eu-west-2&tab=Table#list_parameter_filters=Name:Contains:audit) and checked the params have values.

OLH-1174: Export audit queue parameters

---

.github/workflows/sonarcloud.yaml

Switch all the Github actions to use the same secret and token. Once this is merged I'll delete all the old secrets from this repo.
It seems that at some point since we set up the Sonar scan actions Sonar has changed their access token model. When we set it up we needed to use one token per repository / project. These tokens were migrated from project level to user access tokens based on whoever set up the project initially.
This meant that when the person who set up a lot of these actions left GDS all the tokens were invalidated, preventing us from merging any PRs.
As a stopgap, I've replaced all the tokens with a user token from my account. I've already switched all the secret values to that new token and verified it works for all the projects. This means we can point all of the actions …

BAU: Consolidate Sonar tokens

---

.gitignore
infrastructure/template.yaml

Set up a new [condition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html) to track which environments we want to send logs to Splunk via the CSLS, and apply it to all the lambda log groups. This condition is only true in staging, integration and production, so now we won't send logs to Splunk in our dev or build environments.
Also update the `.gitignore` file so I don't commit the VS code cache folder.
We run our performance (load) tests in build and these generate several GB of logs each run. We share the daily Splunk ingest quota with all of Cabinet Office and we're regularly hitting that quota which means we've been asked to stop sending logs to Splunk when we run performance tests.
It's much simpler to simply not send logs to Splunk in …

OLH-1190: Don't export logs to Splunk in build

---

infrastructure/template.yaml
lambda/write-activity-log/tests/encrypt-data.test.ts

Set up a new SNS topic for the ‘report suspicious activity' messages in the backend template and store the topic ARN in a new secrets manager parameter.
Added section in the template to create both resources

OLH-1242: Set up SNS topic for reporting suspicious activity

---

infrastructure/template.yaml

Turn on the flow of activity log data from TxMA in lower environments up to staging
OLH-857 - Turn on the flow of activity log data from TxMA to the activity log store in staging
Created a new Condition in the backend sam template that’s true if the environment should store activity log data. 
Switch the DynamoDB stream the query-activity-logs lambda uses from the dummy events table to the real raw events table 
So we can start collecting data for users' activity history and test the system end-to-end
1. Deploy to dev
2.  Insert a new valid TxMA event in the raw event store
3. Verify message was picked up and sent to the ActivityLogToFormatQueue

OLH-857 - Turn on the flow of activity log data from TxMA in lower environments up to staging

---

infrastructure/template.yaml

Improve the alarm name for when items are added to the WriteUserServicesDLQ
Change alarm name from  WriteDeadLetterQueueAlarm:  to   WriteUserServicesDeadLetterQueueAlarm:
The alarm name wasn't clear which lambda had gone wrong

addd UserServices into DLQ alarm name to make it clearer

---

infrastructure/template.yaml
lambda/send-event-to-txma/tests/test.json

Linked to https://govukverify.atlassian.net/browse/OLH-1049
Renamed Lambda function definition and associated resources to reduce the name to a value less than 64 char after environment names are prefixed, so for example 
- integration-account-mgmt-backend-send-suspicious-activity-to-txma (Exceeds 64 chars.)
- integration-account-mgmt-backend-send-suspected-activity (Below 64 chars.)
So that the resolved function name does not exceed 64 chars and as a result, we will not be getting this error we are currently getting when deploying to integration environment
`esource handler       SendSuspiciousActivityToTxMAFunction           returned message: "1   validation error       detected: Value        'integration-account-  mgmt-backend-send-     suspicious-activity-   to-txma' at …

OLH-1049 Fix to reduce function name causing length max exceeded Validation

---

infrastructure/template.yaml

Add Dynatrace to backend resources.
Updated template as per Observability teams documentation.
Moved common values to Globals and switched to using the public VPC subnets.
To allow metrics to be shipped to Dynatrace.
Data can be seen in Dynatrace for the dev environment.
When deployed in dev data from interactions with the Account Home page can be seen in Dynatrace.
The process to add Dynatrace is documented in this README https://github.com/govuk-one-login/observability-infrastructure/tree/main/fargate.
You also need to know about this https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3809542559/Dynatrace+VPC+Endpoint page which is not mentioned in the README.

OLH-1213 Add Dynatrace layer to backend lambdas

---

lambda/send-event-to-txma/models.ts
lambda/send-event-to-txma/send-event-to-txma.ts
lambda/send-event-to-txma/tests/send-event-to.txma.test.ts

OLH-1309 - Send audit event timestamps in seconds
For all audit events that we send to TxMA, it now includes three additional fields
- timestamp: number
- event_timestamp_ms: number
- event_timestamp_ms_formatted: string
This allows us to adhere to the structural requirements by TxMA for events they consume.
To adhere to TxMA structural requirements for audit events.
This was requested as a fix to the existing structure we send, see here: https://gds.slack.com/archives/C011Y5SAY3U/p1702391777834979
https://gds.slack.com/archives/C011Y5SAY3U/p1702391777834979
- Deploy to dev environment
-  trigger an audit event
- Verify the structure and content of the event on the _account-mgmt-backend-AuditOutputQueue_ matches expected

OLH-1309 - Send audit event timestamps in seconds

---

infrastructure/template.yaml

This PR merges changes to the template to allow AIS solution to receive notification from the the `UserAccountDeletionTopic` 
- added new mapping section with account numbers for all environment for the AIS solution (please note that dev, build, and staging account numbers are going to be same as in the `CredentialStoreAccounts` mapping, as those accounts are shared between the two solutions)
- added `sns:Subscribe` permission on the `UserAccountDeletionTopic` for AIS accounts 
- added `kms:Decrypt` permission on `SnsKmsKey` for AIS accounts
To allow the AIS solution to receive messages from the UserAccountDeletionTopic

Adding AIS Account Numbers

---

infrastructure/template.yaml

OLH-1355 - Disable Deployment of FormatActivityLog to Prod and Integration
OLH-1355 - Disable Deployment of FormatActivityLog to Prod and Integration
So that TxMA events are not picked up and sent to the activity log database because with the latest changes, the current TxMA events will fail validation and the write to dynamo is timing out
https://govukverify.atlassian.net/browse/OLH-1353 
https://govukverify.atlassian.net/browse/OLH-1352
Deploy successfully to dev environment

OLH-1355 - Disable Deployment of FormatActivityLog to Prod and Integration

---

lambda/format-activity-log/format-activity-log.ts
lambda/format-activity-log/models.ts
lambda/format-activity-log/tests/format-activity-log.test.ts
lambda/format-activity-log/tests/test-helper.ts

OLH-1353 - Align Lambda to Process TxMA Event Structure
Due to the data structure change, an alignment needs to happen, we receive the TxMA event as it is and massage it into the new data structure
So that submitted events can be handled correctly, i.e. we generate an activity log entry, add to the correct Activity log to Write Queue and consequently saved int he activity_log dynamo db table.
Add a valid TxMa event to the raw events table, and it should be picked up, transformed to an activity log and added to the activity log to write queue

OLH-1353 - Align Lambda to Process TxMA Event Structure

---

lambda/format-activity-log/format-activity-log.ts

Remove line which logs the full SQS message when sending.
This lambda was deployed to production for ~45 minutes before we pulled it. During that time it processed 281 messages, errored on each one and logged the full message to Cloudwatch when passing it on to the DLQ. These messages contained user IDs which shouldn't be sent to Cloudwatch or Splunk.
This was likely left in while doing testing and can be safely removed. We already have error handling and sensible log messages for when something goes wrong which include the message ID if we need to retrieve the message later.
https://govukverify.atlassian.net/browse/INCIDEN-657

INCIDEN-657: Don't log full SQS message

---

src/common/model.ts
src/common/redact.ts
src/mark-suspicious-activity-as-reported.ts
src/tests/mark-suspicious-activity-as-reported.test.ts
src/tests/redact.test.ts
src/tests/testFixtures.ts
template.yaml

When a user reports an activity as suspicious, we should record that in the activity log, so that we can ensure we don't report things twice, and provide feedback to the user.
- Create a new lambda, and all the infrastructure that goes along with that (log groups, policies etc...), in the CloudFormation template
- Add a secondary index to the `activity_log` table, so that we can query the table based on the `event_id`
- When the new lambda is triggered, we retrieve the event from the event log (based on the event_id), and update it, setting `reported_suspicious` to `true`
When we build functionality for users to report activity as suspicious, we want to a) give feedback to the user, and b) ensure that we don't make multiple tickets in zendesk.
By setting this flag to true, we can show …

OLH-1053 update reported flag on activity

---

src/delete-activity-log.ts
src/mark-activity-reported.ts
src/tests/delete-activity-log.test.ts
src/tests/mark-activity-reported.test.ts
template.yaml

This PR changes the `activity_log` from using the `timestamp` as the `sort key` to using the `event_id`.
- Rename the `activity_log` table (from `activity_logs` to `activity_log`), this is because DynamoDB key schemas can't be changed after they have been created. By renaming the table, it deletes the old one and creates a new one (there is no data in the table so no need for moving the data over)
- Rename the name for the table name parameter in the CloudFormation template. This is because it is a bit tricky to change a parameter value in CloudFormation once it has been created, so by using a new one, we can avoid having to change the value manually.
- Update the lambdas that used the old `timestamp` property to use `event_id`
- A few minor improvements to the codebase that I spotted. …

OLH-1410 Change the primary key for the activity log table

---

template.yaml

Change the timeout on our audit event queue from the default of 30 seconds to the requested 70 seconds.
TxMA are changing the timeout on their event processing pipeline to 60 seconds. Before they can do that, all event producers need to increase the message visibility on their queues to reflect the new timeout (see [TT2-1450](https://govukverify.atlassian.net/browse/TT2-1450)).
[TT2-1450](https://govukverify.atlassian.net/browse/TT2-1450)
TxMA will be testing this change on their side.
[TT2-1450]: https://govukverify.atlassian.net/browse/TT2-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TT2-1450]: https://govukverify.atlassian.net/browse/TT2-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

OLH-1485: Increase message visibility for audit events

---

template.yaml

Added new policies for the frontend
GENERATOR_KEY_ARN and WRAPPER_KEY_ARN permissions to the frontend for envelop encryption
So the frontend can decrypt data from our activity logs table
https://govukverify.atlassian.net/browse/OLH-1299
https://github.com/govuk-one-login/di-account-management-backend/blob/main/docs/adr/0010-simplify-activity-log-data-structure-pipeline.md
https://github.com/govuk-one-login/di-account-management-frontend/pull/1172
Deployed before deploying frontend PR and tested directly from the frontend
Once deployed navigate to https://home.dev.account.gov.uk/security/sign-in-history 
Activity logs should be displayed in the page

OLH-1299 Add GeneratorKey and WrappingKey to template outputs

---

template.yaml

Updates the template to give permissions to allow the frontend app to publish to the SNS Suspicious Activity Topic
Context [here](https://gds.slack.com/archives/C011Y5SAY3U/p1709733721335279)
Required for [this](https://github.com/govuk-one-login/di-account-management-frontend/pull/1180) to work
Deployed to dev, verified that I can correctly report activity as suspicious

OLH-1459 Publish Suspicious Activity

---

src/send-conf-email.ts
template.yaml

Since now use step functions, we don't need all the lambdas to be subscribed to the SuspiciousActivity topic, since they will be triggered from the step function.
- Remove SNS topic subscriptions
- Remove related resources (DLQs, Policies and Alarms) from the CloudFormation templates
- Remove `DLQ_URL` environment variables
- Remove checks in the code for the `DLQ_URL` environment variable.
I will deploy this to dev, and test the full suspicious activity flow

OLH-1533 Remove unneeded subscriptions to the SuspiciousActivity topic 

---

template.yaml

This deploys the format-activity-logs lambda into integration which means we'll start saving items to the activity logs table.
Nothing else in the template used the `IsNotProdOrIntegration` condition so it's safe to change.
We want to test that data collection is working as expected in integration before we deploy to production. 
I've checked staging where this lambda is already deployed and saving real events. We've got items in the DynamoDB table and Dynatrace is reporting no Lambda errors over the last 72 hours so I'm confident it's all working like we expect.

OLH-1573: Save activity log data in integration

---

src/create-support-ticket.ts
src/send-conf-email.ts
src/tests/create-support-ticket-errors.test.ts
src/tests/create-support-ticket-success.test.ts
src/tests/send-conf-email.test.ts

- Fix issue where the incorrect date and time was appearing in confirmation emails and zendesk tickets
- Add the zendesk ticket ID to emails
- Multiply the timestamp by 1000 (the timestamp is in seconds, the `Date` object expects milliseconds since epoch)
- Add the Zendesk ticket ID to the personalisation object, so we can use it in an email.
These issues came up in testing
Will test on the dev environment.

OLH-1653 & OLH-1564 Send Zendesk ticket ID, and fix issue with incorrect time on emails.

---

src/common/kms-keyring-builder.ts
src/decrypt-data.ts
src/mark-activity-reported.ts
src/tests/decrypt-data.test.ts
src/tests/mark-activity-reported.test.ts
template.yaml

OLH-1530 - Decrypt Activity Log Event Type in Backend
Within Mark Activity as Reported Lambda, we retrieve and decrypt the activity log event type, which is then passed into input into the next lambda in the step functions chain.
So that the event type is displayed in zendesk ticket and TxMA submission in a human readable format.
https://govukverify.atlassian.net/browse/OLH-1530
Deployed to dev, publish a message to Suspicious activity SNS topic with the event ID of the activity log, verify the event type shown in Zendesk ticket is the decrypted version.
Code quality and test completeness.

OLH-1530 - Decrypt Activity Log Event Type in Backend

---

src/send-conf-email.ts
src/tests/send-conf-email.test.ts

Send the fully formatted date and time string to Notify, instead of a seperate date string and time string,
[Context from Dana](https://gds.slack.com/archives/C012GEZBZM0/p1710157972567999?thread_ts=1710155049.156179&cid=C012GEZBZM0)
I was wondering whether there is any advantage of passing event date and event time into the Notify template separately vs passing through the entire date formatted with [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) (which we use[ on the frontend](https://github.com/govuk-one-login/di-account-management-frontend/blob/172beee57f197eb33947b324919f49d8d87666ae/src/utils/prettifyDate.ts#L22), not sure whether you can do the same on the backend but I would have imagined yes since it’s …

OLH-1566 Send time and date as one string to Notify

---

template.yaml

[OLH-1556]
Update suspicious activity report confirmation email template id from GOV.UK notify service
- Template id
- New "GOV.UK One Login Home - March 2024" API key generated in GOV.UK notify 
- /account-mgmt-backend/notify-api-key secret key updated
There is a new confirmation template
[OLH-1556]: https://govukverify.atlassian.net/browse/OLH-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1556 update suspicious activity report confirmation email template id

---

template.yaml

Use the new queue encryption key in integration for our consumer queue out of TxMA.
At some point in the last few months the key for our consumer queue changed in integration which means we're not getting any events through. 
We can't test this without deploying it as use is restricted to our integration account.
Please check the key ARN against the one in my [support request with TxMA](https://gds.slack.com/archives/C02SPF21F7H/p1710241034019199).

BAU: Use the new TxMA key in integration

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

Add the service info for One Login Home in English and Welsh so we can reference it in the emails we send.
This uses the real client IDs for staging, integration and production so we have them available for end to end testing.
We'll be showing sign in events for One Login Home in the activity history. Information about Home isn't in the mapping here because it was copied over from the service card data in the frontend and we don't have a card for Home.
I plan to do a full test of this once I've done the corresponding frontend work to display the Home events.

OLH-1562: Add Home service name for emails

---

template.yaml

This PR refactors the template to store the GOV.UK Notify template ID in the mappings section, then adds the template ID from the 'GOV.UK One Login Test' account to environments up to staging.
We don't want to use the production GOV.UK Notify account and template in staging and below. 
I've deployed this to dev to make sure the syntax is valid

OLH-1581: Use non-prod GOV.UK Notify up to staging

---

template.yaml

OLH-1581 - Set up Zendesk, VPC and GOV.UK Notify in non-production environments
Point to correct secret key arn for zendesk ticket form in all environments
Missed this previously and required for RSA to work end to end
https://govukverify.atlassian.net/browse/OLH-1581
Tested working in all no prod environments

OLH-1581 - Set up Zendesk, VPC and GOV.UK Notify in non-production environments

---

src/common/constants.ts
src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json
src/send-conf-email.ts
src/tests/send-conf-email.test.ts

Include hint text in emails for One Login Home. 
This does hard code the client IDs for the Home frontend, but we have all the rest of the content duplicated here anyway so I didn't think that was too bad. 
I'm using Notify's [Optional content feature](https://www.notifications.service.gov.uk/using-notify/optional-content) to show / hide the hint text line for events about One Login Home.
This relies on a template update which I've made in the Test Notify service. Once the PR is merged I'll apply the same template update to the live service
To explain to users what 'Your GOV.UK One Login Home' means
I've deployed this to dev and triggered an email. I've also checked that the hint text doesn't show up when the variable is set to false.

OLH-1593: Include hint text in emails for One Login Home

---

src/create-support-ticket.ts
src/tests/create-support-ticket-errors.test.ts
src/tests/create-support-ticket-success.test.ts

OLH-1605 - Move user email into custom field/body and remove from Requestor
Code to add the requester email as part of the message body and remove the requester field.
So that TICF still has a way to filter tickets by user, however the generic email sent to new Zendesk users is not triggered. This is needed because the Zendesk configurations required to stop the email generic email from sending did not work without some caveats.
Deploying to dev and test before merging
Code completness and testing

OLH-1605 - Move user email into custom field/body and remove from Requestor

---

src/create-support-ticket.ts
src/tests/create-support-ticket-success.test.ts

OLH-1615 - Fix Issue Authenticating with Zendesk Prod
Add missing token string to cause api token auth vs password auth
So that app can authenticate successfully authenticate against Zendesk api using token 
https://govukverify.atlassian.net/browse/OLH-1615
Test in dev environment, change the dev password to something else, but leave the api token as correct. Should authenticate successfully 
code completeness and test

OLH-1615 - Fix Issue Authenticating with Zendesk Prod

---

src/create-support-ticket.ts
src/tests/create-support-ticket-errors.test.ts

Remove PII from log message when the call to Zendesk fails.
Removed the Zendesk payload from the error log statement.  Updated unit test.
We can't log PII in production and the payload to Zendesk contains various items considered PII.

OLH-1614 - remove PII logging.

---

template.yaml

The step function which manages state when a user reports an activity doesn't need permissions to invoke every lambda function in our account. 
Restrict its access to only the four lambdas it needs to call.
This was flagged as a security hotspot by Sonar.
[Open Sonar findings](https://sonarcloud.io/project/security_hotspots?id=account-management-backend)
I've deployed this dev and checked the step function still runs.

OLH-1639: Restrict which lambdas the step function can invoke

---

.pre-commit-config.yaml
README.md

This will run prettier on all staged files before a new commit is created. If any files are modified, the hook will fail and we'll need to check and stage the changes.
To keep our formatting consistent and reduce the number of linting changes / commits we need to review.
See also https://github.com/govuk-one-login/di-account-management-frontend/pull/1271

BAU: Setup pre-commit to run prettier

---

src/common/model.ts
src/send-suspicious-activity.ts
src/tests/send-suspicious-activity.test.ts

Allow the RSA backend to include the TxMA header value in audit events.
Added new restricted section to the TxMA audit event.
To support fraud analysis.

OLH-1711 - Add new device information to TxMA suspicious activity event.

---

src/common/call-async-step-function.ts
src/common/model.ts
src/mark-activity-reported.ts
src/tests/mark-activity-reported.test.ts
src/tests/testFixtures.ts
src/trigger-rsa-step.ts

OLH-1731 - Ensure RSA Backend Pass the new TxMA Header to Audit Event
Add device_information field when converting from the received SNS event to the object that will be passed across lambdas used as part of the report suspicious activity process.
So that TxMA header us propagated along the chain up to the point where the report suspicious event is sent to TxMA
https://govukverify.atlassian.net/browse/OLH-1731
Deploy to dev, record a suspicious activity and verify device information is sent to TxMA

OLH-1731 - Ensure RSA Backend Pass the new TxMA Header to Audit Event

---

src/config/clientRegistry.cy.json

OLH-1649 - Onboard RP: Find and use a DfE API
Make corrections to link text and service description
Found this as part of UCD review
Fix on top of https://github.com/govuk-one-login/di-account-management-backend/pull/219
UCD Demo

OLH-1649 - Onboard RP: Find and use a DfE API - Make corrections.

---

src/trigger-rsa-step.ts
template.yaml

Enabling canary deployment for our backend lambda's to observe behaviour.
1. Formatted automatically caused by prettier on commit.
2. Conditional to enable canary deployment on dev only.
3. Addition of deployment alarms for all back end lambda's to check for errors.
4. Addition of Code deploy role with Lambda permissions.
5. Enabled Lambda alias auto published with "live".
6. Configured canary deployment to deploy 10% of instances for 5 mins, if there are no errors deploy to all.
To automate rollback in case of errors in newly deployed lambda.
https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3823436177/Lambda+-+Canary+Deployment+Migration+Guidance#Pre-requisites
1. Validated lambda displays live alias.
2. On deployment validated 10% of lambda's have the new version of code.
3. …

OLH-1816-add-a-code-deploy-service-role-to-our-backend-stack

---

template.yaml

[PSREDEV-1154]: added demo environment to mappings.
In template.yaml under Mappings (line 187) the demo environment along with an empty placeholder for the QueueArn and KeyArn have been added.
When trying to deploy the home-stubs pipeline for testing we get the following error - "Error: Failed to create changeset for the stack: home-stubs, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: Unable to get mapping for TxmaDummyInputQueue::demo::QueueArn" the change is to fix this error.
[PSREDEV-1154]: https://govukverify.atlassian.net/browse/PSREDEV-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-1154: added demo environment to mappings

---

pre-merge-integration-tests/README.md
pre-merge-integration-tests/api_call.py
pre-merge-integration-tests/template.yaml

[PSREDEV-1171]: Added pre-merge files.
Added the script api_call.py to poll a cloudformation stack and github role in template.yaml.
Needed to add the files to be able to perform pre-merge checks. 
[PSREDEV-1171]: https://govukverify.atlassian.net/browse/PSREDEV-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-1171: added pre-merge files

---

.github/workflows/publish-to-demo.yaml

[PSREDEV-1163] Added a Verify &Publish to Demo GitHub actions workflow.
A new workflow file publish-to-demo.yaml has been added to .github > workflows.
We need this workflow to be able to deploy the backend into our demo environment in order to test against. We also need the outputs from deploying the backend to get the home-stubs and home-backend AWS pipelines working. 
- Added environment Demo-test and added 3 secrets: 1 for the GitHubActionsRoleArn and 1 for the GitHubArtifactSourceBucketName from the home-backend-pipeline stack and 1 for the SigningProfileName from the aws-signer stack.
- [] Added new environment variable
[PSREDEV-1163]: https://govukverify.atlassian.net/browse/PSREDEV-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-1163: added pubish to demo workflow

---

template.yaml

[PSREDEV-1174]: Changed IsNotDvelopment to IsNotDevelopmentOrDemo along with any refs and added "Demo" under AllowedValues.
To fix an error occurring in the home-backend-pipeline in the di-account-test account. 
[PSREDEV-1174]: https://govukverify.atlassian.net/browse/PSREDEV-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-1174: Changed IsNotDvelopment to IsNotDevelopmentOrDemo

---

template.yaml

We changed these definitions in #260 but Cloudformation is picky and `Equals` must be capitalised.
It also doesn't always like the short form `!Or` function when we have a definition spanning multiple lines, so change that to the full `Fn::Or` form. 
I'm very surprised the linter action didn't catch this - I'll investigate that separately.
Currently our deploys are failing in build.

BAU: Correct typo in condition definition

---

.github/workflows/lint-cloudformation.yaml
.github/workflows/skip-lint-cloudformation.yaml

Fix the trigger conditions on the CFN lint actions so:
1. We run the linter on a pull request whenever `deploy.yaml` is changed
2. We run the 'skip action' on all other pull requests
This must have been broken since we refactored this repo into a single package but we didn't notice because we had the skip action always running on every pull request, which always passes.
This meant that we merged #260 with a malformed Cloudformation template and broke our pipeline. That was addressed separately in #261.

BAU: Trigger the Cloudformation lint action correctly

---

template.yaml

[PSREDEV-1185]: Added demo to mappings of other teams' accounts and resources.
This is needed to deploy account-management-backend template.yaml into the di-account-test account.
[PSREDEV-1185]: https://govukverify.atlassian.net/browse/PSREDEV-1185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-1185: added demo to mappings of other teams

---

.github/workflows/lint-cloudformation.yaml
.github/workflows/skip-lint-cloudformation.yaml

Update the file name so it's looking for changes in the correct place.
In #262 I attempted to fix the Cloudformation linter action.
Everything in there is correct apart from the file name for our template - it's `template.yaml` not `deploy.yaml`. As it was, my updates meant that we'd still never trigger the real linter action since it was looking for changes in a file that doesn't exist.
#262

BAU: Actually fix the Cloudformation linter

---

package-lock.json
package.json

Revert ESbuild and AWS SDK updates. This effectively reverts #259 and #266 as the write-activity-log lambda is failing all requests after them.
The update to ESbuild isn't actually a minor update - going to 0.22.0 breaks how packages are built. See their changelog (https://github.com/evanw/esbuild/blob/main/CHANGELOG.md) and related issues (https://github.com/evanw/esbuild/issues/3819) for more details.
We did already update to ESBuild 0.23.0 which should have solved the problem, but we're still seeing all invocations failing. Let's revert back to a known good config while we understand what's happened.
Please check the version numbers here against the ones in https://github.com/govuk-one-login/di-account-management-backend/pull/259

INCIDEN-839: Revert ESbuild and AWS SDK updates

---

template.yaml

Increase the timeout to 30 seconds for the `write-activity-log` lambda.
The ESBuild reverts in #268 and #270 did fix the problem building the lambdas, but the write activity log lambda was still failing with timeouts.
It turns out this was for a different reason - the input queue for this function was backed up with ~100k events. We have batch sizes of 10 events per invocation, but under normal operation the batches are much smaller than this. This lambda does a lot per event because it has to encrypt and write each to DynamoDB seperately. That meant once it was processing 10 events per invocation these were legitimately timing out because all the operations take longer than 5 seconds.
This is the only lambda that does so much on each invocation. I can see that batches of 10 events are …

INCIDEN-839: Increase write activity log lambda timeout

---

.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
.github/workflows/sam-app-post-merge-actions.yaml

Reverts govuk-one-login/di-account-management-backend#275
We're seeing lambda failures after this release

Revert "BAU: Update upload action to latest v3.9.1"

---

template.yaml

Add a new condition to be clear when we're using external audit events, and use that to only enable the SNS and KMS policies in the correct environments.
We only have account IDs from Orchestration in staging, integration and production environments. This is correct, as those are the only environments that get events from TxMA and therefore where data needs to be deleted.
However, the condition on this policy was to add it in build as well. This caused the deploy to fail as the principal ends up malformed.
See #263 where these were initially added.

OLH-1934: Don't give Orchestration permissions in build

---

.github/workflows/sam-app-post-merge-actions.yaml
post-deploy-tests.Dockerfile
post-deploy-tests/fixtures/delete-activity-log.json
post-deploy-tests/fixtures/write-activity-log.json
post-deploy-tests/run-tests.sh
template.yaml

Set up to run a basic post-deploy integration test. This is following the dev platform team's [instructions](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3054010402/How+to+run+tests+against+your+deployed+application+in+a+SAM+deployment+pipeline).
The test script uses the AWS cli to invoke the `write-activity-log` and`delete-activity-log` lambdas with pre-defined fixtures. It'll fail with a non-zero exit code if either invocation fails.
This is a super-simple integration test, but it checks a lot:
- The lambdas have built correctly and can run
- They have permission to use KMS and DynamoDB
- They can process the message without timing out
Notably this script won't fail if any of the payloads are invalid due to the way we catch and handle errors in the lambdas. That's ok for …

OLH-1949: Set up a basic post-deploy integration test

---

template.yaml

The pipeline provides us with the test container role ARN, but to attach a managed policy to an existing role we need the role name instead.
Thankfully ARNs are a predictable format and are always like
`arn:aws:iam::123456789:role/role-name`
Everything after the `/` is the role name. Use the Cloudformation built in functions to split the ARN and select the second item in the array which is the name.
Currently the backend template is failing to create the test role when it's deployed.

OLH-1949: Provide the role name to the test policy

---

template.yaml

Move the post-deploy test role permissions to the lambda policies.
The deploy pipeline doesn't have permissions to attach a managed policy to the test role. This is the cause of [the error](https://gds.slack.com/archives/C04D3SQNJ4B/p1720537538836309) I saw when enabling the tests in the pipeline:
```
User: arn:aws:sts::301577035144:assumed-role/PL-account-mgmt-backend-pipeline-DeployRole-0a649fe12144/AWS CodeBuild-e6657a15-f8dc-4e88-bb54-3b7bb4025d6e 
is not authorized to perform: iam:AttachRolePolicy on resource: role PL-account-mgmt-backend-pipeline-TestRole-0a649fe12144  
because no identity-based policy allows the iam:AttachRolePolicy action
```
Instead of making one managed policy, we can add the permissions on the lambda side instead which uses only resources created within this …

OLH-1949: Move the test role permissions to the lambda policies

---

post-deploy-tests.Dockerfile
post-deploy-tests/run-tests.sh

Switch to only copying the files we need and use relative file paths for the fixtures so hopefully they can be found when run in the pipeline.
I can run the test container in the pipeline but it fails with `Unable to load paramfile file://post-deploy-tests/fixtures/write-activity-log.json: [Errno 2] No such file or directory:`
I think this is to do with the working directory and where the script is run from. I also realised we don't need to copy the whole repo into the container - we only need the test script and the fixtures for this.
I've built this container locally and run it against `build`.

OLH-1949: Copy test fixtures to Dockerfile root

---

post-deploy-tests/run-tests.sh

Use `cat` to read test fixtures in the post-deploy test script. 
We are still seeing `[Errno 2] No such file or directory` when the test container runs in the pipeline but not locally.
The `file://` URIs are notoriously picky so stop using them completely and switch to using `cat` to read the files in place. This means we need to run the script with bash and not plain sh. I've checked and the Amazon Linux image does include bash.
I can build and run the container locally and the pipeline step is still disabled. Once this is merged I'll go back and re-try it.

OLH-1949: Use `cat` to read test fixtures

---

post-deploy-tests.Dockerfile
post-deploy-tests/fixtures/write-activity-log.json
post-deploy-tests/run-tests.sh

The response we get back from the Lambda service looks like:
```json
{
"StatusCode": 200,
"ExecutedVersion": "60"
}
```
Use JQ to parse this response and check the status code was 200. If it's not, halt processing with exit code 1. This will propagate up and cause the script to exit, failing the tests in Codebuild.
Also increase the `write-activity-log` fixture to 10 messages. This was the original plan for these tests as we discovered that the `write-activity-log` lambda timed out when it processed a full batch of 10 messages on the default timeout settings.
Don't merge this until #305 has been merged into `main`. 
At the moment any errors raised by these tests will be to do with the test setup - either in the script or AWS permissions related. We also need to check the lambda responses …

OLH-1949: Validate lambda invocations in the post-deploy tests

---

post-deploy-tests/run-tests.sh

Extract the testing out into a function and then call the new function iterating over all the lambda names.
We're using the same AWS CLI command to perform the same invocation and same validation step on both lambdas.
This will make it easier and cleaner to add new lambdas in the future if we want to - we'll just need to add a fixture and then update the array on line 18.
#305 and #306 
I've built and run the test container locally against `build`.

OLH-1949: Refactor post-deploy test script

---

template.yaml

[OLH-1948] Add Lambda success rate alarm and alarm for oldest message in a queue
Lambda:
- Check invocations vs errors to trigger an alarm when more than 5% trigger the alarm
Queue:
- If oldest item in queue is older than 5 minutes trigger the alarm 
Improve alerting of errors
Deployed to Dev:
- Observed alarm for a queue with messages longer than 5 minutes
- Graphing for lambda's with error rate > 5%
Currently have an alarm for all lambda's and queues, double check if all are required i.e. Audit Output Queue. This will prevent notification fatigue. 
[OLH-1948]: https://govukverify.atlassian.net/browse/OLH-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1948-add-alarms-to-our-backend-for-lambda-success-rate-and-a-backlog-of-messages-on-sqs

---

src/create-support-ticket.ts
src/delete-activity-log.ts
src/delete-email-subscriptions.ts
src/delete-user-services.ts
src/format-activity-log.ts
src/format-user-services.ts
src/mark-activity-reported.ts
src/query-user-services.ts
src/save-raw-events.ts
src/send-suspicious-activity.ts
src/tests/create-support-ticket-errors.test.ts
src/tests/delete-activity-log.test.ts
src/tests/delete-email-subscriptions.test.ts
src/tests/delete-user-services.test.ts
src/tests/format-activity-log.test.ts
src/tests/format-user-services.test.ts
src/tests/query-user-services.test.ts
src/tests/save-raw-events.test.ts
src/tests/send-suspicious-activity.test.ts
src/tests/trigger-rsa-step.test.ts
src/tests/write-activity-log.test.ts
src/tests/write-user-services.test.ts
src/trigger-rsa-step.ts
src/write-activity-log.ts
src/write-user-services.ts
template.yaml

[OLH-2025]: Reconfigure the backend lambda's so that they all throw error's in the event of failures
Within the handler of each lambda there is a try catch that explicitly throws an error.
Removed manual SQS queue push. 
NOTE: We recognise that this could cause batch processes to be duplicated.
Missing errors from our lamba's as they didn't throw errors. 
This change works well with canary deployments which will allow for automatic roll backs by tracking the success rate alarms.
Error raised in test
Proof of two retries:
Proof message was received by DLQ:
[OLH-2025]: https://govukverify.atlassian.net/browse/OLH-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2025-throw-errors-in-backend-lambdas

---

template.yaml

Updated the `AccountInterventionsService` account ids to reflect the newly created AWS accounts so that these new accounts allow subscriptions to consume notifications from the `UserAccountDeletionTopic` SNS topic.
Account IDs: 
Dev: 484907510598
Build: 565393035754
Staging:  863518416563
AccountInterventionsService allowed accounts for dev, buiold & staging only
Newly commissioned AWS Accounts as part of the OLH transfer of AIS
[ATB-1856](https://govukverify.atlassian.net/browse/ATB-1856)
No functional changes
[ATB-1856]: https://govukverify.atlassian.net/browse/ATB-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-1856: updated AccountInterventionsService AWS Account IDs

---

template.yaml

OLH-1321 - Performance testing: Throttling in several Lambda function during load tests
Add ProvisionedConcurrency to the identified Lambda so that a number of pre-initialized execution environments are allocated to the function. Reduces cold start latency and should stop the throttling.
Update cloudformation template to configure provisioned concurrency
So that cold start are reduced and consequently stops throttling in lamnbdas when under load.
Deploy to dev environment
Run performance test
Check Cloudwatch metrics and confirm no throttling is happening under load.

OLH-1321 - Performance testing: Throttling in several Lambda function

---

template.yaml

OLH-1321 - https://govukverify.atlassian.net/browse/OLH-1321
Add provisioned concurrency to query user service and format user service due to throttle spike. increase to 30 due to write activity log spike which was previously pre-provisioned.
Post performance test, some new lambdas nto rpeviously observed were causing throttling.

OLH-1321 - https://govukverify.atlassian.net/browse/OLH-1321

---

template.yaml

OLH-1321 - Performance testing: Throttling in several Lambda functions during load test
Remove parameterization of provisioned concurrency to allow more flexibility to have different values per lambda.
more flexibility to change value per lambda
Deploy to dev and check updated

OLH-1321 - Performance testing - Remove Parametization of provisioned concurrency

---

template.yaml

[OLH-2292] Rectify metric assigned to Write Activity Log Success Rate Alarm 
Alarm uses Write Activity Log function Metric's instead of another lambda's.
Alarm was using another Lambda's metric's which meant it was going into an alarm state when it shouldn't have.
Deployed to Dev
[OLH-2292]: https://govukverify.atlassian.net/browse/OLH-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2292-rectify-metric-assigned-to-backend-lambda-write-activity-log-function-success-rate

---

src/delete-email-subscriptions.ts
template.yaml

[OLH-2293] Resolve Delete Email Subscription not picking up latest secret value from Secrets Manager
Implemented Version ID for Publishing API Token. If the key changes in the future the version id will need to be updated in cloud formation, triggering the code deploy that will actually get the new secret from secret's manager. 
Cloud formation did not update the secret value in the lambda on deployment as the section of code that check's did not change. This is as cloud formation only updates stuff that changes in the template.yaml file. Moving forward we will be forced to deploy an updated version ID which will trigger the Lambda to have an updated value. NOTE: We should not manually update the value in the environments as this will break cloud formation. We opted not to get the …

OLH-2293-delete-email-subscription-lambda-failing-in-production

---

template.yaml

[OLH-2293] Add parameter to enable skip canary deployment
Addition of LambdaDeploymentPreference parameter which is required for skip canary deployment.
To allow canary deployments to be skipped
Deployed to Dev
[OLH-2293]: https://govukverify.atlassian.net/browse/OLH-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2293 Add parameter to enable skip canary deployment

---

template.yaml

Reverts govuk-one-login/di-account-management-backend#446
This is to force update the secret value.

Revert "[OLH-2293] force cloud formation update [skip canary]" [skip canary]

---

package-lock.json
package.json
src/redrive-delete-email-subscriptions.ts
src/tests/redrive-delete-email-subscriptions.test.ts
template.yaml

[OLH-2296] Implement a lambda to redrive event's in DLQ for the delete email subscription lambda
Implemented a lambda that takes SQS from the delete email subscription lambda DLQ and send's them as an SNS event to the delete email subscription lambda.
290 failed events are in the DLQ in production and cannot be processed through AWS.
Deployed to Dev and used SQS event from prod to validate successful completion of Lambda.
[OLH-2296]: https://govukverify.atlassian.net/browse/OLH-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2296 create a re drive lambda to process events in delete email subscription dlq

---

template.yaml

[OLH-2296] Shorten name of lambda to meet AWS requirements of less than 64 characters
Changed name of lambda to be shorter
AWS has a limit of 64 characters for function names. When deployed to production, it exceeds the character limit.
[OLH-2296]: https://govukverify.atlassian.net/browse/OLH-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2296 create a re drive lambda to process events in delete email subscription dlq rename lambda [skip canary]

---

template.yaml

[OLH-2296] Disable event source mapping for redrive lambda
Disabled event source mapping
There will be failures in the future that we need to identify and resolve. Leaving the event source mapping will cause the lambda to constantly retry failed events.
[OLH-2296]: https://govukverify.atlassian.net/browse/OLH-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OLH-2296] Disable event source mapping for redrive lambda

---

.github/workflows/pre-merge.yaml
.github/workflows/publish-to-demo.yaml
pre-merge-integration-tests/api_call.py
pre-merge-integration-tests/template.yaml
sonar-project.properties

OLH-2228 - Write a pre-merge test for a real use case of OLH
Update Python script to include test for the writing an activity log and checking the activity log is recorded in dynamo.
So that we get pre-merge testing to do real regression test against the one login home service
Deploy to demo environment, trigger pre-merge testing and confirm it runs successfully

OLH-2228 - Write a pre-merge test for a real use case of OLH

---

.github/workflows/pre-merge.yaml

OLH-2303 - Trigger Pre-merge test to validate as part of Github Merge queue
Define new trigger and filter to ensure only run in mere queue
Attempting to make pre-merge a part of OLH release process

Define new trigger and filter to ensure only run in merge queue

---

.github/workflows/lint-cloudformation.yaml
.github/workflows/pre-merge.yaml
README.md

Added pre-merge related doc to readme
Check for keyword in the last commit only
Ensured pre-merge check runs and its not skipped when merging to main

Remove conditional from check pre-merge. skipPreMerge

---

.github/workflows/lint-cloudformation.yaml
.github/workflows/pre-merge.yaml
README.md

OLH-2303 - Trigger Pre-merge test to validate as part of Github Merge
Make pre-merge a part of OLH release process by doing the following:
Ensure merge to main is via a merge queue
As part of status check before merge, do a pre-merge test run. This process deploys the merge candidate to a test environment and carries out a series of end to end test, if all passes, proceeds with the merge
Define new trigger and filter to ensure only run in mere queue
Add ability to skip pre-merge test by including skipPreMerge in last 3 commits
Make pre-merge testing a part of OLH release process. 
Created a branch with similar configurations as the main branch, created a pr against that branch and demonstrated a successful pre-merge test run when skipPreMerge text is not in the last 3 commits messages and …

OLH-2303 - Trigger Pre-merge test to validate as part of Github Merge

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-2352 - Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services
Add new service card info to translations files for english and welsh.
Add English info for the welsh in this case as this service card has no welsh translation.
Add translations for demo environment
Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services
https://govukverify.atlassian.net/browse/OLH-2352
https://govukverify.atlassian.net/browse/DIOT-691

OLH-2352 - Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services

---

src/format-user-services.ts
src/tests/format-user-services.test.ts
src/tests/testUtils.ts

[OLH-2399] Drop HMRC events & Fix last seen pretty
Dropped HMRC event's as they are not OLH users.
Last seen pretty isn't meant to be used but is still available in the database. Updating to the correct value so the table will fix itself over time. 
HMRC are sending event's to be processed when they shouldn't be. This has filled up our user_services table with 5m records that shouldn't be there. 
Last seen pretty date was expected in milliseconds turned out to be seconds in production and was too late to fix.
Deployed to Dev and validated that hmrc event's were not processed by pushing event's were different client_ids to the sns user_services format queue. 
[OLH-2399]: https://govukverify.atlassian.net/browse/OLH-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …

OLH-2399-stop-tx-ma-sending-us-the-wrong-data

---

src/remove-hmrc-events.ts
src/tests/remove-hmrc-events.test.ts
template.yaml

Supported scan pagination and batch deletions.
there was too much to delete in production so need to break up the scan command and batch write command. Batch write has a limit of 25 and scan supports pagination.

Olh 2404 delete data from user services table that shouldnt be there

---

.github/workflows/sonarcloud.yaml

The sonarcloud-github-action is now deprecated. The recommendation is to replace it with the sonarqube-scan-action. This should work as a drop-in replacement.
Implemented Sonarqube Scan to prepare for migration when our existing sonarqube cloud action is deprecated.
Sonarqube Cloud Action is being deprecated and replaced with Sonarqube scan.
https://github.com/sonarsource/sonarcloud-github-action
Workflow working in this PR.

BAU: update sonar cloud gh action source

---

template.yaml

BAU - Performance Optimisations
Previously provisioned concurrency was added to facilitate the NFR which had a high number of users per second. This NFR was set too high and did not take into account real world traffic. Whilst this NFR is being adjusted, we are reverting our configuration to save costs. Additionally, provisioned concurrency is not required for the backend as we are aiming for eventual consistency. This means lambda cold start times do not matter and the queues will ensure they are completed.
Save costs ~$300 per month
Deployed to Dev and ran a performance test against it

removed provisioned concurrency

---

package-lock.json

OLH-2378 - Update SignedIn URL for Immigration Advice Authority
Update SignedIn URL for Immigration Advice Authority RP
To provide a more user friendly experience for signed in card user
https://govukverify.atlassian.net/browse/OLH-2378
Deploy to dev for UCD review

OLH-2378 - Update SignedIn URL for Immigration Advice Authority

---

template.yaml

Revoke IPV Core access to the deletion topic. We can also clear up the respective mapping entries.
The Core team have told us they're now listening for the account deleted audit events instead of messages on this topic, so we can safely revoke their access.
See https://gds.slack.com/archives/C012GEZBZM0/p1741863821328419
[ADR 0189](https://github.com/govuk-one-login/architecture/blob/main/adr/0189-account-deletion-processing.md)

OLH-2522: Revoke IPV Core access to the deletion topic

---

.github/workflows/lint-cloudformation.yaml

Pin cfn-lint to 1.29.1
cfn-lint 1.30.0 introduced a new rule to check IAM permissions. Something in that new rule is causing false warnings when run against our template (see
https://github.com/aws-cloudformation/cfn-lint/issues/4035 for more details).
For now, pin to the latest working version. We'll be able to remove this pin again once we've figured out the issue.
You can verify the behaviour by running cfn-lint locally:
```bash
pip install cfn-lint==1.30.0
cfn-lint -t template.yaml # gives the false warnings
pip install cfn-lint=1.29.1
cfn-lint -t template.yaml # no warnings
```

BAU: Pin cfn-lint to 1.29.1

---

.github/workflows/lint-cloudformation.yaml

Unpin cfn-lint in the PR / post-merge Github actions.
In #580 we pinned to an old version of cfn-lint to avoid a bug. That bug's been fixed (see https://github.com/aws-cloudformation/cfn-lint/pull/4041) so we can unpin and get the latest version.
I did consider leaving the pin in place to avoid these sorts of errors in the future, but it'd add another dependency upgrade that we'd have to look for, test and upgrade manually and I vaguely remember a conversation from a while back where we decided that that wasn't worth the tradeoff.
You can install the latest version locally to verify it runs on our backend template with no errors:
```bash
pip install --upgrade cfn-lint # gets the new 1.32.0
cfn-lint -t template.yaml -r "eu-west-2" # Runs with no errors
```

BAU: Unpin cfn-lint

---

template.yaml

Remove eVCS access to delete topic.
This service no longer needs access to our topic as it's switched over to consuming the `AUTH_DELETE_ACCOUNT` audit events.
https://govukverify.atlassian.net/browse/OLH-2470

OLH-2470: Remove eVCS access to delete topic

---

template.yaml

Update Lambda runtime to Node 22 from Node 18 as that's about to be deprecated. Our policy[^1] says we should be on the most recent LTS runtime, so that's Node 22.
This is a safe upgrade as we already run our tests locally and in CI using Node 22
[^1]: https://team-manual.account.gov.uk/policies/#active-policies
Node 18 will be deprecated in September.

OLH-2538: Update Lambda runtime to Node 22

---

src/remove-hmrc-events.ts
src/tests/remove-hmrc-events.test.ts
template.yaml

[BAU] Refactor HMRC data delete script to continue from the last evaluated key
enabled passing in the last evaluated key as a env var
In production there are too many records in the activity log table for it to be processed within the 15 min lambda limit. 
This change will allow us to continue from the last completed instead of iterating through all the records that have already been checked. 
Deployed to dev and tested.

Bau refactor hmrc data delete script

---

package-lock.json
src/format-activity-log.ts
src/format-user-services.ts
src/tests/format-activity-log.test.ts
src/tests/format-user-services.test.ts
template.yaml

[OLH-2404] Trigger an Alarm if we receive a unexpected TXMA Event Client ID
Added a check against the rp registry for the txma client ID.
If the ID doesn't match any of the IDs in the client registry, it logs a warning.
This warning is picked up by a log filter and in turn raises an alarm. 
This will let us know if there is a unexpected txma client ID event and potentially allow us to quickly respond to bad data entering our databases.
Improve monitoring for unexpected client ids being processed to our databases.
Deployed and tested in Dev.
[OLH-2404]: https://govukverify.atlassian.net/browse/OLH-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2404 warn if unexpected txma client

---

package-lock.json
src/format-activity-log.ts
src/format-user-services.ts
src/tests/format-activity-log.test.ts
src/tests/format-user-services.test.ts
template.yaml

[OLH-2404] Filter out internal RPs in Backend Lambda's
Following the implementation of the internal category in the RP registry, we are now about to filter out data that doesn't need to to enter out database.
Orgnaise known RPs.
[OLH-2404]: https://govukverify.atlassian.net/browse/OLH-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2404 filter out internal RPs

---

package-lock.json
template.yaml

[OLH-2294] Point SNS topics and Permissions to alias live version of backend Lambda's
Pointed SNS topics and permissions to live version of lambda's.
We introduced the live alias following the implementation of canary deployments. However, some of the event triggers were still pointing to the function instead of the live alias. This meant that during canary deployment, the wrong lambda versions were being tested for some lambda's.
Deployed to dev and validated.
[OLH-2294]: https://govukverify.atlassian.net/browse/OLH-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2294 backend lambda event triggers are not pointing to live alias

---

.gitlint
.husky/commit-msg
.pre-commit-config.yaml
README.md

- Removed `pre-commit` config and README instructions as it is no longer used as Husky is used for Git hooks instead
- Added Gitlint config
- Added Gitlint instructions to README
- Added `commit-msg` Git hook using Husky which pipes the commit message to Gitlint
To ensure commit messages are consistently formatted, including the Jira ticket number
https://govukverify.atlassian.net/browse/OLH-2644

OLH-2644: add commit message linting

---

template.yaml

[OLH-2357] Increase Lambda Timeouts
Increased the query-user-services lambda timeout to 10s
Increased the write-user-services lambda timeout to 10s
These lambda's intermittently timeout due to down stream cold starts. They do make their way back to a DLQ and get retried. With this change it will allow for the existing Lambda process to execute. When the downstream cold starts are completed, we can still expect the lamdba to execute in less than 5s.
https://govukverify.atlassian.net/browse/OLH-2357
[OLH-2357]: https://govukverify.atlassian.net/browse/OLH-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2357: Increase lambda timeouts

---

template.yaml

Hardcodes the Dynatrace layer ARN. This is not the latest ARN which will come in a subsequent PR.
There’s a bug in the `{{resolve:secretsmanager}}` syntax that prevents the current configuration from deploying the latest available Dynatrace layer. The fix is to just hardcode the layer ARN and manually keep it up to date.

OLH-3061: hardcode Dynatrace layer ARN

---

template.yaml

Update the global configuration for our lambdas to use all 3 availability zones, now the new VPC has subnets in all of them. I will keep an eye on this as it rolls out.
I've deployed the branch to dev and it all looks ok there.
This will cover us in a disaster situation where 2 of the 3 AZs go down.

OLH-2976: Use all 3 subnets in the new VPC

---

template.yaml

Temporarily remove this alarm as it's causing every integration deployment to fail at the canary check stage.
I've deployed this to dev to check Cloudformation is happy with the empty list.
I think there's something not working in the Lambda, so doing this will allow us to make deployments again while we investigate and fix whatever's broken.
https://gds.slack.com/archives/C011Y5SAY3U/p1759139968080249

BAU: Don't alarm on delete email deploy errors
