govuk-one-login/di-account-management-backend

.gitignore
infrastructure/samconfig.toml
infrastructure/template.yaml
lambda/format-user-services/format-user-services.ts
lambda/format-user-services/package.json
lambda/query-user-services/package.json
lambda/query-user-services/query-user-services.ts

Various fixes to get to the point of a basic deploy

GUA-248 Amend Cloudformation

---

lambda/write-user-services/write-user-services.ts

Since writing this first lambda function we've worked out how to use `Promise.all()` and `Array.map()` to iterate over all the records in an event body. This functional programming approach is more in the spirit of the Airbnb style guide and means we can drop the 'no await in loop' rule exemption.
Refactor the handler function here to use the same method as the others.

BAU: Refactor handler to match other lambdas

---

infrastructure/samconfig.toml

Let's make it match the work that is going on over in:
https://github.com/alphagov/di-authentication-account-management/pull/607/

BAU: Rename stackname across all envs

---

infrastructure/template.yaml

- Use the `enhanced-vpc` generated in the frontend app 
- Configure the config on the lambda function .
- Give the lambda policy the correct access.

GUA-500 Add vpc and relevant roles to the lambda

---

infrastructure/template.yaml
lambda/delete-user-services/.eslintrc.json
lambda/delete-user-services/delete-user-services.ts
lambda/delete-user-services/jest.config.ts
lambda/delete-user-services/models.ts
lambda/delete-user-services/package-lock.json
lambda/delete-user-services/package.json
lambda/delete-user-services/tsconfig.json

- Add cloud formation for delete stack components as defined in [0005-deleting-service-usage-in-account.md](https://github.com/alphagov/di-account-management-backend/blob/main/docs/adr/0005-deleting-service-usage-in-account.md)
- Add placeholder basic files for `delete-user-services` so `sam build` and `sam deploy` works
The lambdas do need to work, as there's a [follow up ticket to write and test them properly](https://govukverify.atlassian.net/jira/software/c/projects/GUA/boards/195?modal=detail&selectedIssue=GUA-469).
What we do need is to get enough basic components in place so we can `sam deploy` successfully.

GUA-467 Cloudformation for delete stack

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/sam-app-post-merge-actions.yaml
lambda/save-raw-events/.eslintrc.json
lambda/save-raw-events/jest.config.ts
lambda/save-raw-events/models.ts
lambda/save-raw-events/package-lock.json
lambda/save-raw-events/package.json
lambda/save-raw-events/save-raw-events.ts
lambda/save-raw-events/tests/save-raw-events.test.ts
lambda/save-raw-events/tsconfig.json

- This lambda reads from the SQS queue and saves the TXma event without modification to the raw_events table .
- Update the GitHub workflows to run the tests on merge .

GUA-486 Save raw Events 

---

lambda/query-user-services/models.ts
lambda/query-user-services/package-lock.json
lambda/query-user-services/package.json
lambda/query-user-services/query-user-services.ts
lambda/query-user-services/tests/query-user-services.test.ts

- Use the dynamodb util unmarshall function to unmarshall the DynamoDbrecord to TxmaEvent.
- Update tests to reflect the changes.

GUA- 485 Unmarshall db stream

---

infrastructure/template.yaml

Create `DeleteTopicArnParameter` to allow us to pick up the ARN in https://github.com/alphagov/di-authentication-account-management/pull/690
Also lint some whitespace out of the templates.

GUA-470: publish sns topic ssn

---

lambda/format-user-services/format-user-services.ts
lambda/format-user-services/tests/format-user-services.test.ts
lambda/query-user-services/query-user-services.ts
lambda/save-raw-events/save-raw-events.ts
lambda/write-user-services/write-user-services.ts

Spotted this along the way, We should improve this for better error messages

BAU: improve error logging

---

infrastructure/template.yaml

Enable TxMA for integration / prod:
https://govukverify.atlassian.net/wiki/spaces/TMA/pages/3369893941/SQS+Integration+Details+-+Accounts

GUA-462: Wire up TxMA to service store

---

infrastructure/template.yaml

GUA-426: Remove conditional filter for production / integration

---

infrastructure/template.yaml

to access SNS topic and related key

Added some permissions for IPV Core accounts

---

SECURITY.md

Seems like both a sensible thing to do in it's own right. And also brings our repo into pairty with our frontend application:
https://github.com/alphagov/di-account-management-frontend
see: https://github.com/alphagov/di-account-management-frontend/pull/810

GUA-547: Add Vulnerability Disclosure Policy as md file

---

.github/workflows/publish-to-dev.yaml

- Add a workflow to deploy to dev .
- Add the backend pipeline stack by following (https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3059908609/How+to+deploy+a+SAM+application+with+secure+pipelines?NO_SSR=1)
- Update the secrets in the repository.

GUA-711: Add workflow to publish to dev

---

infrastructure/template.yaml

Enroll Account Bravo's credential store into the [SNS delete topic](https://github.com/alphagov/di-account-management-backend/blob/main/docs/adr/0005-deleting-service-usage-in-account.md)

GUA-323: Subscribe Accounts Bravo to the delete SNS Topic

---

lambda/delete-user-services/package-lock.json
lambda/format-user-services/package-lock.json
lambda/query-user-services/package-lock.json
lambda/save-raw-events/package-lock.json
lambda/write-user-services/package-lock.json

Dependency Updates for our lambdas

---

infrastructure/template.yaml

We think this adds to resiliency, and matches good SRE practice we see coming out of the Bravo Team

BAU: Add third subnet

---

lambda/delete-email-subscriptions/package-lock.json
lambda/delete-email-subscriptions/package.json
lambda/delete-user-services/package-lock.json
lambda/delete-user-services/package.json
lambda/format-user-services/package-lock.json
lambda/format-user-services/package.json
lambda/query-activity-log/package-lock.json
lambda/query-activity-log/package.json
lambda/query-user-services/package-lock.json
lambda/query-user-services/package.json
lambda/save-raw-events/package-lock.json
lambda/save-raw-events/package.json
lambda/write-activity-log/package-lock.json
lambda/write-activity-log/package.json
lambda/write-user-services/package-lock.json
lambda/write-user-services/package.json

https://github.com/alphagov/di-account-management-backend/security/dependabot

Update client dynamo and client sqs to upgrade version of vulnerable fast-xml-parser 

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/sam-app-post-merge-actions.yaml
.github/workflows/sonarcloud.yaml
infrastructure/template.yaml
lambda/format-activity-log/.eslintrc.json
lambda/format-activity-log/format-activity-log.ts
lambda/format-activity-log/jest.config.ts
lambda/format-activity-log/models.ts
lambda/format-activity-log/package-lock.json
lambda/format-activity-log/package.json
lambda/format-activity-log/sonar-project.properties
lambda/format-activity-log/tests/format-activity-log.test.ts
lambda/format-activity-log/tests/test-helper.ts
lambda/format-activity-log/tsconfig.json

Adds a Lambda that:
Reads in an from the sqs queue and formats the data into a structure to write in dynamodb
The output is written to a subsequent SQS queue

GUA 748 format activity log

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/sam-app-post-merge-actions.yaml
.github/workflows/sonarcloud.yaml
infrastructure/template.yaml
lambda/delete-activity-log/.eslintrc.json
lambda/delete-activity-log/delete-activity-log.ts
lambda/delete-activity-log/jest.config.ts
lambda/delete-activity-log/models.ts
lambda/delete-activity-log/package-lock.json
lambda/delete-activity-log/package.json
lambda/delete-activity-log/sonar-project.properties
lambda/delete-activity-log/tests/delete-activity-log.test.ts
lambda/delete-activity-log/tests/test-helpers.ts
lambda/delete-activity-log/tsconfig.json
lambda/delete-email-subscriptions/package-lock.json

Lambda to delete records in the activity log store, triggered by subscription to the account deletion SNS topic

GUA 748 delete activity log

---

lambda/delete-activity-log/delete-activity-log.ts

- Dynamo Db paginates the query at 10 MB , this process will make sure that if there are more records all of them are queried before a deletion is performed .

GUA-887: Update query to continue till all records are read

---

.github/workflows/lint-and-test-lambdas.yaml
.github/workflows/sonarcloud.yaml
lambda/stubs/account-management-api/.eslintrc.json
lambda/stubs/account-management-api/account-management-api-stub.ts
lambda/stubs/account-management-api/jest.config.ts
lambda/stubs/account-management-api/package-lock.json
lambda/stubs/account-management-api/package.json
lambda/stubs/account-management-api/sonar-project.properties
lambda/stubs/account-management-api/tests/account-management-api-stub.test.ts
lambda/stubs/account-management-api/tsconfig.json

This lambda responds to API Gateway events and always returns 204 status code and an empty body. This conforms with the [stub specification](https://github.com/alphagov/di-account-management-backend/blob/main/docs/stubs/account-management-api/openapi.yaml).
I had hoped to build this API stub completely with API Gateway mock integrations, but they're only supported on API Gateway v1 for HTTP APIs. V1 doesn't have default routes or a fixed 'live' URL so we'd need ~100 lines of Cloudformation per stubbed API route to define the route, method, integration and response template.
Instead I thought it'd be easier to understand if we had a single lambda which generates the response then use API Gateway v2 and a default route to forward all requests to the lambda. This'll mean we end up with fewer …

GUA-874: Create lambda for AM API stub 

---

lambda/delete-activity-log/delete-activity-log.ts
lambda/delete-activity-log/tests/delete-activity-log.test.ts
lambda/delete-email-subscriptions/delete-email-subscriptions.ts
lambda/delete-user-services/delete-user-services.ts
lambda/delete-user-services/tests/delete-user-services.test.ts
lambda/format-activity-log/format-activity-log.ts
lambda/format-user-services/format-user-services.ts
lambda/format-user-services/tests/format-user-services.test.ts
lambda/query-activity-log/query-activity-log.ts
lambda/query-user-services/query-user-services.ts
lambda/save-raw-events/save-raw-events.ts
lambda/save-raw-events/tests/save-raw-events.test.ts
lambda/write-activity-log/tests/write-activity-log.test.ts
lambda/write-activity-log/write-activity-log.ts
lambda/write-user-services/tests/write-user-services.test.ts
lambda/write-user-services/write-user-services.ts

Update lambdas to not log any data from the TXMA event.

OLH-902 : Update Logging to exclude logging personal data from txma events

---

lambda/delete-email-subscriptions/delete-email-subscriptions.ts

PII data user_id was being logged when error happened . 
Removed this data from being logged .
PII data should not be logged in Production .

Remove PII data logging

---

lambda/query-activity-log/decrypt-data.ts
lambda/query-activity-log/tests/decrypt-data.test.ts

Add validation for Access Check Value that is added  in the encryption step.
Add validation for Access Check Value and tests.
Changes were not done as apart of MVP in the previous PR, now included them .

Add Validation for the access check value environment variable

---

infrastructure/template.yaml

Upgrade the the latest version of the secure pipeline.
The account-mgmt-backend-pipeline cloud formation was upgraded to the latest version of the deployment template.
The dependency on the frontend stack was removed.
There shouldn't be any dependencies in the backend resources on frontend resources.
Pipeline stacks updated and build from main deployed to DEV.  This branch was then deployed to check the dependency on the frontend resource had been successfully removed. 
The important aspect of this is to confirm the pipeline can be updated and the new version of the backend stack deployed over the existing deployments, particularly production.

OLH-1068 - Upgrade to latest version of secure deployment pipeline.

---

infrastructure/template.yaml

Remove VPC logs CSLS subscription
This is failing to deploy with permissions errors which look to be outside our team.
Remove the new subscription so we can unblock the pipeline while we investigate.

OLH-1217: Remove VPC logs CSLS subscription

---

docs/adr/0008-report-a-suspicious-activity.md
infrastructure/template.yaml
lambda/send-event-to-txma/.eslintrc.json
lambda/send-event-to-txma/Readme.md
lambda/send-event-to-txma/constants.ts
lambda/send-event-to-txma/jest.config.ts
lambda/send-event-to-txma/models.ts
lambda/send-event-to-txma/package-lock.json
lambda/send-event-to-txma/package.json
lambda/send-event-to-txma/send-event-to-txma.ts
lambda/send-event-to-txma/sonar-project.properties
lambda/send-event-to-txma/tests/send-event-to.txma.test.ts
lambda/send-event-to-txma/tests/test-helpers.ts
lambda/send-event-to-txma/tests/validator.test.ts
lambda/send-event-to-txma/tsconfig.json
lambda/send-event-to-txma/validator-rules.ts
lambda/send-event-to-txma/validator.ts

OLH-1049 Send an audit event to TxMA when a user submits a report
We create a Lambda that’s subscribed to the suspicious activity SNS topic, so that when the lambda receives a message, it will generate the audit event and send it to the audit event SQS queue. TxMA will pick up messages from the Audit Event Queue
1. A new lambda that sends events to TxMA - This handler for this Lambda is built to be generic such that when another Lambda needs to send a message to TxMA(i.e. put a message on the audit event SQS queue, tall they will need to do is add a validation rule, add their transformation logic to convert the received event to a TxMA event and configure their Lambda within the infrastructure code, the transformation logic and validation rule is selected by an event name, so as part of …

OLH-1049 Send an audit event to TxMA when a user submits a report

---

lambda/write-activity-log/models.ts
lambda/write-activity-log/package-lock.json
lambda/write-activity-log/package.json
lambda/write-activity-log/tests/test-helpers.ts
lambda/write-activity-log/tests/write-activity-log.test.ts
lambda/write-activity-log/write-activity-log.ts

Use the new data model to write to the activity log table.
wite-activity-log accepts new data model as input from format-activity-log lambda and writes new format to DynamoDB table.  The event_id is envelope encrypted.
We have a new data mode for the activity log.

OLH-1298 Modify the write-activity-log lambda to use the new data model.

---

docs/adr/0004-store-all-event-data.md
infrastructure/template.yaml
lambda/format-activity-log/format-activity-log.ts
lambda/format-activity-log/models.ts
lambda/format-activity-log/package-lock.json
lambda/format-activity-log/package.json
lambda/format-activity-log/tests/format-activity-log.test.ts
lambda/format-activity-log/tests/test-helper.ts

Use the new data model, such that when new activity log TXMA Events are added to the dynamo, we format correctly as per new data model before adding to the Queue for write to the activity log table.
JIRA: https://govukverify.atlassian.net/browse/OLH-1297
Picks up TXMA event of activity log as per new model and generate an activity log that is consumable by the write activity log lambda.
To align with the new data model for thew activity log.
1. Navigate to dev environment
2. Add a new valid record to the Dynamo DB with TxMA Event structure as per new data model
3. Should add an ActivityLogEntry to the ActivityLogToWriteQueue
4. Add a new invalid record to  Dynamo DB
5. Should add an entry to the FormatActivityLogDeadLetterQueue
Sample correct new TxMA Event as per new model …

OLH-1297 - Modify the format-activity-log Lambda to use the new data model

---

.github/workflows/sam-app-post-merge-actions.yaml

Fix GitHub action to deploy to build (and higher envs) to match the one used for dev.
Added manifest parameter to sam build that allows it to be run in the root folder.
Removed the working directory parameter for SAM deploy as its no longer needed.
Restructure changed the way the artefacts were built by SAM.
Only when merged to main and building.

OLH-1111 fix issue in GitHub action for build env.

---

README.md
package-lock.json
package.json
src/common/constants.ts
src/common/model.ts
src/create-support-ticket.ts
src/tests/create-support-ticket-errors.test.ts
src/tests/create-support-ticket-success.test.ts
src/tests/send-event-to.txma.test.ts
src/tests/testFixtures.ts
src/tests/validator.test.ts
template.yaml

JIRA: https://govukverify.atlassian.net/browse/OLH-1052
Create a new lambda that sends a ticket using the Zendesk API
1. New Lambda and SAMs template
2. New Secrets to be added across all envs for interacting with Zendesk
What the Lambda does
1. Ensure all environment variables required to successfully connect to, create ticket and send to Zendesk are provided
2. Validates the fields in the received event
3. Retrieves the values for the environment variable keys in AWS Secrets
4. Validates that values exist for the required keys - these include zendesk api credentials, groups, etc
5. Creates a zendesk ticket and sends to Zendesk
6. If any of the steps above fails, send the SNS record to DLQ for retry later
So that fraud team are alerted when a suspicious activity is reported and have a …

OLH-1052 - Create a new lambda that sends a ticket using the Zendesk API

---

template.yaml

I missed the change of a name of a handler, causing the build to fail
I have deployed this to the dev environment and verified that it works

OLH-1053 fix incorrect handler name

---

docs/adr/0011-reporting-suspicious-activity.md

New ADR documenting decision to use Step Functions.
New ADR added that documents the decision to use Step Functions.
The current approach is not as good as that offered by Step Functions.

OLH-1389 Redesign the backend for reporting a suspicious activity

---

package-lock.json
package.json
report-suspicious-activity-asl.json
src/common/call-async-step-function.ts
src/common/constants.ts
src/common/model.ts
src/common/utils.ts
src/common/validator-rules.ts
src/create-support-ticket.ts
src/decrypt-data.ts
src/mark-activity-reported.ts
src/send-conf-email.ts
src/send-suspicious-activity.ts
src/tests/call-async-step-function.test.ts
src/tests/create-support-ticket-errors.test.ts
src/tests/create-support-ticket-success.test.ts
src/tests/decrypt-data.test.ts
src/tests/mark-activity-reported.test.ts
src/tests/send-conf-email.test.ts
src/tests/send-event-to.txma.test.ts
src/tests/testFixtures.ts
src/tests/trigger-rsa-step.test.ts
src/tests/validator.test.ts
src/trigger-rsa-step.ts
template.yaml

OLH-1454 - Use a step function to manage the backend lambdas
Introduced a new Step Function Implementation for reporting suspicious activities, as part of this, the following changed:
- New Lambda was introduced to trigger the step function, the lambda subscribes to the Suspicious Activity Topic.
- Removed DLQ error handling for all lambdas used within the step function
- Changed the mark activities as reported lambda to work with step functions.
- Changed the create and send Zendesk ticket lambda to work with step functions and update the activity log with the zendesk ticket ID
- Changed the send acknowledgement email to work with step functions
- Changed the Send to TxMA lambda to work with Step function
- New requirements for reporting suspicious activities were also implemented as …

OLH-1454 - Use a step function to manage the backend lambdas

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-1649 - Onboard RP: DfE Find and Use an API
Create a new entry in translation file for all environments
So that New Dfe services can be mapped correctly as part of RSA.
Deployed to dev, use Dfe services, verify RSA works with it

OLH-1649 Onboard RP: Find and use a DfE API

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

Onboard new MoJ service.
Updated client registries
MoJ onboarding

OLH-1589 - Onboard MOJ Ressettlement Passport.

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

Onboard Welsh fisheries service. 
Updated the client registries.
Onboarding Welsh fisheries service

OLH-1648 - onboard Wales fisheries permit service.

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-1376 - Onboard RP: Immigration Advice Authority [prev: OISC]
update translation files
So that RSA Email can refer to the correct service names
https://govukverify.atlassian.net/browse/OLH-1376

OLH-1376 - Onboard RP: Immigration Advice Authority [prev: OISC]

---

.github/dependabot.yml

BAU: add dependabot

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-1878 - Adjust RP: Immigration Advice Authority
Update RP info as per latest provided here: https://govukverify.atlassian.net/browse/OLH-1878
To ensure RP information matches the latest info the RP provided.
https://govukverify.atlassian.net/browse/OLH-1878
Deploy to dev and get a UCD review

OLH-1878 - Adjust RP: Immigration Advice Authority

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

This adds the "Visit someone in prison" service to the translation files so that it can be referenced in the report suspicious activity email.
The "Visit someone in prison" service is due to onboard on the 24th June.

OLH-1880: Add Visit someone in prison service

---

.github/workflows/lint-cloudformation.yaml
template.yaml

[OLH-1904]
tamplate.yaml has been updated to fix the errors reported by cfn-lint@1.3.3
So that publishing to backend repo to dev can work successfully
Ran cfn-lint locally to ensure no errors are reported
Run cfn-lint locally
[OLH-1904]: https://govukverify.atlassian.net/browse/OLH-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1904 Fix CFN-lint errors on template.yaml

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-1908] Onboard RP: ATE Capital Schemes [PB]
Added the correct production id and testing id to both english and welsh translation files
ATE Capital Schemes service is being onboarded
Tested locally
[OLH-1908]: https://govukverify.atlassian.net/browse/OLH-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1908 Onboard ATE Capital Schemes [PB]

---

.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
.github/workflows/sam-app-post-merge-actions.yaml

This is required so we can use the new enriched build notifications to Slack
Update upload action to latest v3.9.1
This is required so we can use the new enriched build notifications to Slack
See also https://github.com/govuk-one-login/di-account-management-frontend/pull/1498
I'll test this by deploying to dev using the new action version on this branch

BAU: Update upload action to latest v3.9.1

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

This adds the content for the new FAA service to the clientRegistry JSON files
The service is onboarding on the 8th of July. These changes are so that it can be referenced in the report suspicious activity email.
https://govukverify.atlassian.net/browse/OLH-1927

OLH-1927: Onboard Find an apprenticeship

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
.github/workflows/sam-app-post-merge-actions.yaml
package-lock.json
package.json
template.yaml

[OLH-1954] Upgrade esbuild to v0.23
Added more flags to the Metadata sections for each lambda based on AWS recommendations
I have also added an additional Banner options to address the following error:
```
"Error: Dynamic require of \"os\" is not supported",
"    at file:///var/task/write-activity-log.mjs:1:479",
"    at exports (/tmp/tmp2g39fyph/node_modules/@smithy/shared-ini-file-loader/dist-cjs/getHomeDir.js:4:14)",
"    at file:///var/task/write-activity-log.mjs:1:590",
"    at <anonymous> (/tmp/tmp2g39fyph/node_modules/@smithy/shared-ini-file-loader/dist-cjs/index.js:33:25)",
"    at file:///var/task/write-activity-log.mjs:1:590",
"    at <anonymous> (/tmp/tmp2g39fyph/node_modules/@smithy/node-config-provider/dist-cjs/index.js:65:37)",
"    at …
```

OLH-1954 Upgrade esbuild to v0.23

---

README.md

Add a section to the README that explains what the Dockerfile is for and how to run it locally against the build environment.

OLH-1949: Document how to run the test container

---

template.yaml

[PSREDEV-1240]:  Adding environment configuration values for demo environment
Adding values for demo environment in environment configuration
Required to deploy di-account-management-backend in testing account. 
- [] No environment variables or secrets were added or changed
[PSREDEV-1240]: https://govukverify.atlassian.net/browse/PSREDEV-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding environment configuration values for demo environment

---

template.yaml

PSREDEV-1243: Adding environment variables for demo environment
Adding environment variables for demo environment
Required to deploy di-account-management-backend in testing account. Currently codepipeline is throwing the following error: Unable to get mapping for EnvironmentVariables::demo::GOVACCOUNTSPUBLISHINGAPIURL as this does not exist in the template

Adding environment variables for demo environment

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

Add content for the driving with a medical condition service to the client registry files
These changes are the service can be referenced in the report suspicious activity email.
https://govukverify.atlassian.net/browse/OLH-1975

OLH-1975: Driving with a medical condition RP

---

src/create-support-ticket.ts
src/delete-activity-log.ts
src/delete-email-subscriptions.ts
src/delete-user-services.ts
src/format-activity-log.ts
src/format-user-services.ts
src/mark-activity-reported.ts
src/query-user-services.ts
src/save-raw-events.ts
src/send-conf-email.ts
src/send-suspicious-activity.ts
src/tests/format-activity-log.test.ts
src/trigger-rsa-step.ts
src/write-activity-log.ts
src/write-user-services.ts

[OLH-1947] add processing logs to the back end lambda's
Console.logs added the start and end of the process
Unaware of errors.
Deployed to dev and observed errors.
[OLH-1947]: https://govukverify.atlassian.net/browse/OLH-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1947-add-processing-logs-to-our-backend-lambdas

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-1963 - Onboard RP: Use (& View) an LPA
Update config files to include the new RP
Onboarding the use and view a lasting power of attorney RP
Deploy to dev and sign off by UCD.

OLH-1963 - Onboard RP: Use (& View) an LPA

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

Add translations for the PDP connect service to the client registry JSON files. 
This is to ensure that the service appears in the report suspicious activity confirmation email.
Checked the content and service ID against the translations provided in the onboarding ticket.

OLH-2002: Onboard PDP Connect RP

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-1965] Rework ATE capital schemes
Updated Card text in english and welsh.
Updated by service.
[OLH-1965]: https://govukverify.atlassian.net/browse/OLH-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-1965-rework-rp-ate-capital-schemes-pb

---

.husky/pre-commit
src/common/encrypt-data.ts
src/tests/encrypt-data.test.ts
src/write-activity-log.ts
template.yaml

[OLH-2065]: Improve Lambda performance
Ran performance tests against dev. Identified Lambda's were under provisioned and rightsized them. Additionally refactored some code so it has better performance.
Lambda's were taking 1.8s to run in the 99th percentile. 
Deployed to Dev. 
Validated performance improvement.
[OLH-2065]: https://govukverify.atlassian.net/browse/OLH-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2065-help-performance-testing-team-fix-99-test-failures-after-introducing-the-stub-page

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2111] Onboard RP DFE Claim additional Payments for Teaching
Addition of onboarding parameters.
https://govukverify.atlassian.net/browse/DIOT-394
Content review by Mel, deployed to Dev.
[OLH-2111]: https://govukverify.atlassian.net/browse/OLH-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2111-onboard-rp-df-e-claim-additional-payments-for-teaching

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json
src/send-conf-email.ts
template.yaml

[OLH-2110] Resolved RSA issues in Demo account
Addition of logging to help with future debugging
Added client registry
Updated secret key
Resolve issues in Demo account
Deployed and validated working in Demo account.
[OLH-2110]: https://govukverify.atlassian.net/browse/OLH-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2110-invesitgate-why-rsa-send-confirmation-email-step-does-not-work-in-demo-account

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-2118 - Onboard RP: Companies House - Accounts
Add translation definitions for new service card for company house accounts
So that service cards can be produced correctly for company house accounts users
Deploy to dev and get UCD review
Design updates should be signed off by a UCD person prior to the PR being open for dev review

OLH-2118 - Onboard RP: Companies House - Accounts

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2152] Update companies house signed in state url
Replaced link href due to request from companies house
Requested to change link.
[OLH-2152]: https://govukverify.atlassian.net/browse/OLH-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated sign in state url for companies House

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-2150 - Add Welsh translations for DWP's integration clients
https://govukverify.atlassian.net/browse/OLH-2150
Update existing integration translations to include welsh and added new lower environment integrations for the same services.
So that DWP can end to end test their one login service card in welsh language
Deploy to dev and test presence of card.

OLH-2150 - Add Welsh translations for DWP's integration clients

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2195] DWP Minor Content Update
Changed from: Go to your repay and manage benefit money you owe account
Change to: Go to your Repay and manage benefit money you owe account
Request from DWP
[OLH-2195]: https://govukverify.atlassian.net/browse/OLH-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updated translation

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2173] Onboard DBT Apply for import License
Onboarded DBT Apply for import license
Onboarding new service
[OLH-2173]: https://govukverify.atlassian.net/browse/OLH-2173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added service to client registry for DBT Apply for import license

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2172] Onboard DBT Apply for import License
Onboarded DBT Apply for Export Certificate
Onboarding new service
[OLH-2172]: https://govukverify.atlassian.net/browse/OLH-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2172-onboard-rp-department-for-business-trade-apply-for-an-export-certificate-2

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2198] Onboard Defra Dangerous Dox Index
Onboarded new service Defra Dangerous Dog Service
[OLH-2198]: https://govukverify.atlassian.net/browse/OLH-2198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2198-defra-dangerous-dog-index

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2171] Onboard HMPO Cancel a lost or stolen passport
Onboarded the new service HMPO cancel a lost or stolen passport
[OLH-2171]: https://govukverify.atlassian.net/browse/OLH-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2171-onboard-rp-hmpo-cancel-a-lost-or-stolen-passport

---

scripts/README.md
scripts/onboard-rp.py
sonar-project.properties

[OLH-2246] Automate onboarding RPs using script
Addition of a script that updates the frontend and backend translation files using user inputs.
Automatically updates the config.ts file adding the RP to the allowed list.
Automate repetitive behaviour.
Does not deploy and should only be run locally.
Ran locally and successfully onboarded OLH 2230.
Run script with dummy values.
[OLH-2246]: https://govukverify.atlassian.net/browse/OLH-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2246-automate-onboarding-r-ps

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2230] Onboard RP DFE Teaching Vacancies
created using automation - please double check if anything is out of the ordinary
[OLH-2230]: https://govukverify.atlassian.net/browse/OLH-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2230-onboard-rp-df-e-teaching-vacancies

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2120] Onboard RP Ofgem Local Authority Flexibility eligibility
Onboarded RP
Deployed to dev
[OLH-2120]: https://govukverify.atlassian.net/browse/OLH-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2120-onboard-rp-ofgem-la-flexible-eligibility

---

README.md

[OLH-2293] Minor change to trigger skip canary deployment in production
[OLH-2293]: https://govukverify.atlassian.net/browse/OLH-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2293-delete-email-subscription-lambda-failing-in-production [skip canary]

---

template.yaml

[OLH-2293] force cloud formation update [skip canary]
Removed secret assign as it has not been refreshed. This will force an update as tested in Dev. This PR will be reverted to then force the correct secret value to be assigned.
Cloud formation is not updated secret value.
Deployed to dev to force update secret value. 
[OLH-2293]: https://govukverify.atlassian.net/browse/OLH-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OLH-2293] force cloud formation update [skip canary]

---

CODEOWNERS

Correct the name of the approving team

BAU: update codeowners

---

.github/workflows/pre-merge.yaml

Test merge queue validation triggering pre-merge checks

Olh 2228 test branch protection

---

.github/workflows/pre-merge.yaml
pre-merge-integration-tests/api_call.py

Olh 2228 test merge queue

---

post-deploy-tests.Dockerfile

Resolve code smells in backend
Consolidated docker file run configuration to one line
To resolve code smells in the backend

Resolved code smells

---

scripts/onboard-rp.py
src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2316] Onboard RP DFE Qualified Teacher Status
Onboard new RP.
Refactored onboarding script to be more readable.
[OLH-2316]: https://govukverify.atlassian.net/browse/OLH-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2316 onboard rp qts

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-2271 - Onboard RP: DfE - Check a family's eligibility [Private beta]
OLH-2229 - Onboard RP: CO - Find a tender [Private Beta]
OLH-2352 - Onboard RP: DBTrade: Apply for a licence to provide sanctioned trade services [Super Private Beta]
Added new clientRegistry entries for check a family eligibility for school meals, Find a Tender and Apply for a licence to provide sanctioned trade services 
To onboard new RPs

OLH-2271, OLH-2229, OLH-2352 - Onboard RPs (DfE - Check a family's eligibility, CO - Find a tender, DBTrade)

---

src/config/clientRegistry.en.json

OLH-2303 - Trigger Pre-merge test to validate as part of Github Merge queue
Define new trigger and filter to ensure only run in mere queue
Attempting to make pre-merge a part of OLH release process

Testing pre-merge.

---

.github/workflows/pre-merge.yaml
src/config/clientRegistry.en.json

Olh 2303 pre merge

---

.github/workflows/pre-merge.yaml

Add skipPreMerge

---

.github/workflows/pre-merge.yaml

Test pre-merge process.

---

.github/workflows/pre-merge.yaml

Testing when skip pre merge test is false.

testing with skip test is false.

---

.github/workflows/pre-merge.yaml

Test where skip pre-merge is false

add logging for skip pre merge.

---

.github/workflows/pre-merge.yaml

Test where skip pre merge is true

with skipPreMerge

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

I copied over the client registries from frontend using the following command...
```
cat ../di-account-management-frontend/src/locales/cy/translation.json| jq ".clientRegistry" > src/config/clientRegistry.cy.json
cat ../di-account-management-frontend/src/locales/en/translation.json| jq ".clientRegistry" > src/config/clientRegistry.en.json
```

OLH-2170 Oboard RP Air Pollution Archive

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

Onboard Home Office DBS Check RP

---

src/config/clientRegistry.cy.json

OLH-2386 - Change welsh signed-in link.
Change welsh signed-in link.
COnfirmed post merge to main that the link should be slightly different

OLH-2386 - Change welsh signed-in link. skipPreMerge

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

[OLH-2423] Update Sign in state URL for Apply Teacher Training
Updated sign in state url
New URL provided 
[OLH-2423]: https://govukverify.atlassian.net/browse/OLH-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2423-update-signed-in-state-url-for-apply-for-teacher-training

---

src/config/clientRegistry.cy.json
src/config/clientRegistry.en.json

OLH-2378 - Update the service card: HO - IAA Home Service Card
Update the IAA Home Service card
Update the IAA Home Service card

OLH-2378 - Update the service card: HO - IAA Home Service Card

---

package-lock.json

OLH-2391 - 02/25 Onboard RP: Welsh Gov - Rural Payment Wales
Add new RP Rural Payment Wales
Onboard new RP Rural Payment Wales
https://govukverify.atlassian.net/browse/OLH-2391
Deploy to dev and carry out UCD review
Signed off by a member of the UCD team

OLH-2391 - 02/25 Onboard RP: Welsh Gov - Rural Payment Wales

---

package-lock.json

OLH-2531 - Onboard RP HO: Foreign Influence Registration Scheme
Add new Client - Foreign Influence Registration Scheme
Onboarding new RP
https://govukverify.atlassian.net/browse/OLH-2531
https://govukverify.atlassian.net/browse/DIOT-461

OLH-2531 - Onboard RP HO: Foreign Influence Registration Scheme

---

package-lock.json
src/tests/send-conf-email.test.ts

[OLH-2521] Onboard RP ICS DESNZ CHMM
Update RP Registry to the latest version
Mocked the rp registry in the unit tests
[OLH-2521]: https://govukverify.atlassian.net/browse/OLH-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update rp registry

---

src/remove-hmrc-events.ts
template.yaml

[OLH-2404] Update Delete Script to point to activity log table
Script will now delete from the acitivity log table.
As the activity log table uses composite id's, I had to use the partition key and the sort key. 
To delete bad data from the activity log table.
[OLH-2404]: https://govukverify.atlassian.net/browse/OLH-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bau refactor hmrc data delete script

---

package-lock.json

BAU - update rp registry which includes hoDors

Update di-account-management-rp-registry for hoDors

---

package-lock.json

[OLH-2737] Onboard Gov UK app
Onboarded Gov UK app to RP registry
[OLH-2737]: https://govukverify.atlassian.net/browse/OLH-2737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2737 06 25 onboard rp co gds gov uk app

---

package-lock.json

Updates to the latest RP registry version

BAU: update to latest RP registry

---

package-lock.json

Update the RP registry to the latest version

BAU: update RP registry

---

template.yaml

Updates to Dynatrace layer ARN to the latest version

OLH-3061: hardcode latest dynatrace layer arn [skip canary]

---

package-lock.json

Update the RP registry to the latest version

OLH-2660: update RP registry

---

.github/workflows/pre-merge.yaml
.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
package-lock.json

OLH-2736 Onboard RP: CO: National Security & Investment
Add new RP for public beta
So National Security & Investment can be onboarded
https://govukverify.atlassian.net/browse/OLH-2736
https://govukverify.atlassian.net/browse/DIOT-1154

OLH-2736 Onboard RP: CO: National Security & Investment

---

package-lock.json

Bumps the RP registry to the latest version

OLH-3065: bump RP registry

---

package-lock.json

Updates the RP registry to the latest version

OLH-3182: update RP registry in backend
